/**
 * Art Director sub-agent.
 *
 * Runs BEFORE image generation. Takes a content brief + campaign context and
 * emits a structured **visual concept brief**: composition, focal point,
 * real subjects, reference image URLs (from KB visual_reference collection),
 * style notes, and banned elements.
 *
 * Why: today asset.ts feeds a text prompt + brand colors straight into
 * image-gen, producing generic stock-AI shapes that hit the palette but miss
 * the actual product/feature/message. The Art Director closes that gap by
 * grounding every image in the real product (via KB visual_reference docs)
 * and explicitly naming what NOT to make.
 *
 * Output is JSON — concept-to-prompt.ts then translates the brief into the
 * provider-specific prompt + reference URLs the image model accepts.
 */
import { generateText } from "ai";
import { z } from "zod";
import pino from "pino";
import type { CpClient } from "@marketing/cp-client";
import type { LlmModel } from "@marketing/shared-types";
import { getLanguageModel } from "../llm-registry";
import { recordLlmUsage } from "../usage";
import { kbSearch, type KbSearchHit } from "../kb";
import { findBrandGuidance } from "../brand-guidance";

const log = pino({ name: "art-director" });

export type ArtDirectorInput = {
  /** What the content is about (the message / angle / feature). */
  request: string;
  /** Optional content body — gives the AD context for what the image must reinforce. */
  contentBody?: string;
  /** Channel hint affects composition/aspect (e.g. linkedin = square poster). */
  channel?: string;
  campaignId?: string;
  cp: CpClient;
  model?: LlmModel;
  threadRef?: string | null;
  jobId?: string | null;
  workflowRunId?: string | null;
};

export type VisualConceptBrief = {
  /** One-sentence summary the LLM judge can compare candidates against. */
  concept_summary: string;
  /** Composition + camera framing notes ("isometric 3/4 view, hero shot of bridge UI"). */
  composition: string;
  /** What the eye lands on first ("the cross-chain transaction approval modal"). */
  focal_point: string;
  /** Real subjects that MUST appear (product UI elements, real diagrams, etc). */
  real_subjects: string[];
  /** KB documentIds whose metadata.image_url should be passed to image-gen as imageInput. */
  reference_image_urls: string[];
  /** Stylistic notes ("clean editorial, restrained palette, soft cool light"). */
  style_notes: string;
  /** What this image must NOT be — fed to negative prompts. */
  banned_elements: string[];
  /** Provenance — for debugging + the asset-judge's tie-back to KB. */
  references_from_kb: Array<{
    documentId: string;
    title: string;
    similarity: number;
  }>;
};

/**
 * Default banned aesthetics — the things every "AI-looking" generation slips
 * into when given only colors. Caller can extend.
 */
export const DEFAULT_BANNED_AESTHETICS = [
  "generic abstract shapes",
  "anonymous floating geometric cubes",
  "stock 3D crypto coin",
  "generic Ethereum diamond",
  "rainbow gradients on black",
  "wireframe globe",
  "robotic hands typing",
  "person staring at futuristic UI from behind",
  "neon city skyline",
  "matrix code rain",
];

const ConceptSchema = z.object({
  concept_summary: z.string().min(8),
  composition: z.string().min(4),
  focal_point: z.string().min(4),
  real_subjects: z.array(z.string()).default([]),
  reference_image_urls: z.array(z.string().url()).default([]),
  style_notes: z.string().default(""),
  banned_elements: z.array(z.string()).default([]),
});

const ART_DIRECTOR_PROMPT = `You are the Art Director for a product-driven marketing team.
Your job is to design ONE specific visual concept for a piece of content. The
piece will then be generated by an image model with reference image
conditioning.

Rules of the road:
- The concept MUST name the actual product feature or message — never
  abstract / generic.
- Pull real subjects (product UI, real diagrams, signature motifs) that
  the image model can ground itself in.
- When a KB reference image fits, ALWAYS include its url in
  reference_image_urls. The image model uses these as visual conditioning,
  not just inspiration.
- Style notes describe lighting / mood / palette, NOT subject. Subjects go
  in real_subjects.
- Banned elements MUST include the failure modes you'd reject if this
  came back from a designer — the things that would make this look like
  every other AI-generated post.
- Output ONLY valid JSON. No markdown fence, no commentary.`;

export async function runArtDirector(
  input: ArtDirectorInput,
): Promise<VisualConceptBrief> {
  // Gather KB references (visual + brand + product) BEFORE the LLM call so
  // the brief is grounded in reality, not imagination.
  const [visualHits, brandHits, productHits, brandGuidance] = await Promise.all([
    kbSearch({
      query: input.request,
      collectionKinds: ["visual_reference"],
      campaignId: input.campaignId,
      k: 4,
    }),
    kbSearch({
      query: `brand visual language for ${input.channel ?? "marketing"}`,
      collectionKinds: ["brand"],
      campaignId: input.campaignId,
      k: 3,
    }),
    kbSearch({
      query: input.request,
      collectionKinds: ["product"],
      campaignId: input.campaignId,
      k: 3,
    }),
    findBrandGuidance({ topic: `visual ${input.request}`, limit: 3 }),
  ]);

  const referenceUrls = visualHits
    .map((h) => extractImageUrl(h))
    .filter((u): u is string => Boolean(u));

  const userMessage = buildUserMessage({
    request: input.request,
    contentBody: input.contentBody,
    channel: input.channel,
    visualHits,
    brandHits,
    productHits,
    brandGuidance,
    suggestedReferenceUrls: referenceUrls,
  });

  const { text, usage, experimental_providerMetadata } = await generateText({
    model: getLanguageModel(input.model),
    system: ART_DIRECTOR_PROMPT,
    prompt: userMessage,
  });

  await recordLlmUsage({
    agent: "art-director",
    model: input.model,
    threadRef: input.threadRef ?? undefined,
    jobId: input.jobId ?? null,
    workflowRunId: input.workflowRunId ?? null,
    usage,
    providerMetadata: experimental_providerMetadata,
  });

  let parsed: z.infer<typeof ConceptSchema>;
  try {
    const jsonText = stripFence(text);
    parsed = ConceptSchema.parse(JSON.parse(jsonText));
  } catch (err) {
    log.warn(
      { err: (err as Error).message, raw: text.slice(0, 400) },
      "art-director output failed to parse; falling back to skeleton",
    );
    parsed = fallbackBrief(input.request);
  }

  // Merge default bans, dedupe.
  const banned = uniq([...DEFAULT_BANNED_AESTHETICS, ...parsed.banned_elements]);

  return {
    concept_summary: parsed.concept_summary,
    composition: parsed.composition,
    focal_point: parsed.focal_point,
    real_subjects: uniq(parsed.real_subjects),
    reference_image_urls: uniq([...parsed.reference_image_urls, ...referenceUrls]),
    style_notes: parsed.style_notes,
    banned_elements: banned,
    references_from_kb: visualHits.map((h) => ({
      documentId: h.documentId,
      title: h.documentTitle,
      similarity: h.similarity,
    })),
  };
}

function buildUserMessage(args: {
  request: string;
  contentBody?: string;
  channel?: string;
  visualHits: KbSearchHit[];
  brandHits: KbSearchHit[];
  productHits: KbSearchHit[];
  brandGuidance: Array<{ source: string; text: string; similarity: number }>;
  suggestedReferenceUrls: string[];
}): string {
  const visualSection = args.visualHits.length
    ? "\n\n# KB Visual References\n" +
      args.visualHits
        .map(
          (h, i) =>
            `[${i + 1}] ${h.documentTitle} (${(h.similarity * 100).toFixed(0)}%)\n${h.body.slice(0, 300)}\nimage_url: ${extractImageUrl(h) ?? "(none)"}`,
        )
        .join("\n\n")
    : "\n\n# KB Visual References\n(none — flag this in concept_summary if a real product reference is essential)";

  const productSection = args.productHits.length
    ? "\n\n# Product facts\n" +
      args.productHits
        .map((h) => `- ${h.documentTitle}: ${h.body.slice(0, 200)}`)
        .join("\n")
    : "";

  const brandSection =
    args.brandHits.length || args.brandGuidance.length
      ? "\n\n# Brand visual guidance\n" +
        [
          ...args.brandHits.map((h) => h.body),
          ...args.brandGuidance.map((g) => g.text),
        ]
          .map((t) => t.slice(0, 200))
          .join("\n\n")
      : "";

  const channelLine = args.channel ? `\nChannel: ${args.channel}` : "";

  return `Design a visual concept for this piece of content.${channelLine}

# Request
${args.request}
${args.contentBody ? `\n# Content body excerpt\n${args.contentBody.slice(0, 1_200)}` : ""}
${visualSection}
${productSection}
${brandSection}

# Suggested reference URLs (carry forward unless they don't fit)
${args.suggestedReferenceUrls.length ? args.suggestedReferenceUrls.join("\n") : "(none)"}

Return JSON matching:
{
  "concept_summary": "...",
  "composition": "...",
  "focal_point": "...",
  "real_subjects": ["..."],
  "reference_image_urls": ["..."],
  "style_notes": "...",
  "banned_elements": ["..."]
}`;
}

function extractImageUrl(hit: KbSearchHit): string | null {
  const meta = hit.documentMetadata as { image_url?: unknown } | undefined;
  if (typeof meta?.image_url === "string" && meta.image_url) return meta.image_url;
  const chunkMeta = hit.metadata as { image_url?: unknown };
  if (typeof chunkMeta?.image_url === "string" && chunkMeta.image_url) {
    return chunkMeta.image_url;
  }
  return null;
}

function stripFence(text: string): string {
  const m = /```(?:json)?\s*\n([\s\S]*?)\n```/i.exec(text);
  return m && m[1] ? m[1] : text.trim();
}

function fallbackBrief(request: string): z.infer<typeof ConceptSchema> {
  return {
    concept_summary: `Visual for: ${request.slice(0, 120)}`,
    composition: "centred hero shot, generous negative space, isometric 3/4 view",
    focal_point: "the specific product feature mentioned in the request",
    real_subjects: [],
    reference_image_urls: [],
    style_notes: "clean editorial, restrained palette, soft cool light",
    banned_elements: [],
  };
}

function uniq<T>(arr: T[]): T[] {
  return Array.from(new Set(arr));
}
