#!/usr/bin/env node
/**
 * Load smoke test: Phase 10 Day 4.
 * Creates 50 content items (draft → approved → enqueue) and verifies
 * the queue drains within 5 minutes with no duplicates.
 *
 * Usage:
 *   CP_BASE_URL=http://localhost:3000 INTERNAL_API_TOKEN=... node load-smoke.mjs
 *
 * Channels exercised: internal_blog (always), + linkedin / x if env vars set.
 * Daily caps must be set high enough (e.g. 100) to avoid throttling.
 */

import assert from "node:assert";

const BASE = process.env.CP_BASE_URL ?? "http://localhost:3000";
const TOKEN = process.env.INTERNAL_API_TOKEN ?? "";
const TOTAL_JOBS = Number(process.env.LOAD_SMOKE_JOBS ?? "50");
const TIMEOUT_MS = 5 * 60 * 1000; // 5 minutes

const channels = ["internal_blog"];
if (process.env.LINKEDIN_ACCESS_TOKEN) channels.push("linkedin");
if (process.env.X_ACCESS_TOKEN) channels.push("x");

const headers = {
  "content-type": "application/json",
  "x-internal-token": TOKEN,
};

async function cp(method, path, body) {
  const res = await fetch(`${BASE}${path}`, {
    method,
    headers,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`CP ${method} ${path} → ${res.status}: ${text}`);
  }
  return res.json();
}

// --- Setup: one campaign for all load items ---
async function setup() {
  const slug = `load-smoke-${Date.now()}`;
  const campaign = await cp("POST", "/api/campaigns", {
    slug,
    name: `Load Smoke ${new Date().toISOString()}`,
    phase: "launch",
  });
  console.log(`[setup] campaign created: ${campaign.id} (${campaign.slug})`);
  return campaign;
}

// --- Create one content item, approve it, return contentId ---
async function createAndApprove(campaignId, index) {
  // 1. Create content.
  const content = await cp("POST", "/api/content", {
    campaignId,
    type: "post",
    stage: "push",
    title: `Load Smoke Post ${index}`,
    bodyMd: `# Load Smoke Post ${index}\n\nThis is a synthetic post generated by the load smoke test at ${new Date().toISOString()}.`,
  });

  // 2. Submit for review.
  await cp("POST", `/api/content/${content.id}/submit`, {});

  // 3. Get the pending approval.
  const approvals = await cp("GET", `/api/approvals?contentId=${content.id}`);
  const approval = Array.isArray(approvals) ? approvals[0] : approvals;
  if (!approval?.id) throw new Error(`No approval found for content ${content.id}`);

  // 4. Approve it.
  await cp("POST", `/api/approvals/${approval.id}`, { decision: "approved", decidedBy: "load-smoke" });

  return content.id;
}

// --- Enqueue a publish job for each channel ---
async function enqueue(contentId, channel, index) {
  const job = await cp("POST", "/api/publish-jobs", {
    contentId,
    channel,
    // Stagger by 100ms to avoid bursting the BullMQ worker too hard.
    scheduledAt: new Date(Date.now() + index * 100).toISOString(),
  });
  return job.id;
}

// --- Poll until all jobs succeed or timeout ---
async function waitForDrain(jobIds) {
  const deadline = Date.now() + TIMEOUT_MS;
  const pending = new Set(jobIds);
  const failed = [];

  console.log(`[drain] waiting for ${pending.size} jobs to complete...`);

  while (pending.size > 0 && Date.now() < deadline) {
    await new Promise((r) => setTimeout(r, 3000));
    const batch = [...pending];
    for (const id of batch) {
      const job = await cp("GET", `/api/publish-jobs/${id}`).catch(() => null);
      if (!job) continue;
      if (job.status === "succeeded") {
        pending.delete(id);
      } else if (job.status === "failed") {
        pending.delete(id);
        failed.push({ id, error: job.error });
      }
    }
    console.log(`[drain] remaining: ${pending.size} | failed: ${failed.length}`);
  }

  return { timedOut: pending.size > 0, remaining: [...pending], failed };
}

// --- Check for duplicate externalIds ---
async function checkDuplicates(jobIds) {
  const externalIds = [];
  for (const id of jobIds) {
    const job = await cp("GET", `/api/publish-jobs/${id}`).catch(() => null);
    if (job?.externalId) externalIds.push(job.externalId);
  }
  const unique = new Set(externalIds);
  return { total: externalIds.length, unique: unique.size, hasDuplicates: externalIds.length !== unique.size };
}

// --- Main ---
async function main() {
  console.log(`\n=== Load Smoke Test: ${TOTAL_JOBS} jobs across [${channels.join(", ")}] ===\n`);

  const campaign = await setup();
  const start = Date.now();

  // Create and approve content items in parallel (10 at a time).
  const contentIds = [];
  const batchSize = 10;
  for (let i = 0; i < TOTAL_JOBS; i += batchSize) {
    const batch = await Promise.all(
      Array.from({ length: Math.min(batchSize, TOTAL_JOBS - i) }, (_, j) =>
        createAndApprove(campaign.id, i + j + 1),
      ),
    );
    contentIds.push(...batch);
    console.log(`[prepare] ${contentIds.length}/${TOTAL_JOBS} content items approved`);
  }

  // Enqueue each content item for a channel (round-robin across channels).
  const jobIds = [];
  for (let i = 0; i < contentIds.length; i++) {
    const channel = channels[i % channels.length];
    const jobId = await enqueue(contentIds[i], channel, i);
    jobIds.push(jobId);
  }
  console.log(`[enqueue] ${jobIds.length} publish jobs enqueued`);

  // Wait for drain.
  const { timedOut, remaining, failed } = await waitForDrain(jobIds);
  const elapsed = ((Date.now() - start) / 1000).toFixed(1);

  console.log(`\n=== Results (${elapsed}s) ===`);
  console.log(`Total jobs:  ${jobIds.length}`);
  console.log(`Succeeded:   ${jobIds.length - remaining.length - failed.length}`);
  console.log(`Failed:      ${failed.length}`);
  console.log(`Timed out:   ${remaining.length}`);

  if (failed.length > 0) {
    console.log("\nFailed jobs:");
    failed.forEach((f) => console.log(`  ${f.id}: ${f.error}`));
  }

  // Check for duplicate externalIds.
  const { total, unique, hasDuplicates } = await checkDuplicates(jobIds);
  console.log(`\nDuplicate check: ${unique}/${total} unique external IDs → ${hasDuplicates ? "⚠️  DUPLICATES FOUND" : "✅ no duplicates"}`);

  // Assertions.
  assert.ok(!timedOut, `FAIL: ${remaining.length} jobs did not complete within ${TIMEOUT_MS / 1000}s`);
  assert.strictEqual(failed.length, 0, `FAIL: ${failed.length} jobs failed`);
  assert.ok(!hasDuplicates, "FAIL: duplicate externalIds detected");

  console.log(`\n✅ Load smoke passed: ${jobIds.length} jobs in ${elapsed}s\n`);
}

main().catch((err) => {
  console.error("LOAD SMOKE FAILED:", err.message);
  process.exit(1);
});
