"use client";

// Client renderer for the /creation-workflow page. Splits jobs into
// "Active" (running or just-finished) and "Recent" sections, renders each
// as a step pipeline with planning input, output preview, and any image
// thumbnails generated by the asset sub-agent.
//
// State only — no fetch logic here. The server component re-runs on
// realtime invalidation (RealtimeInvalidator subscribes to the table).

import { useEffect, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import {
  CHANNELS,
  type Channel,
  type LlmProvider,
} from "@marketing/shared-types";

export type StepView = {
  id: string;
  name: "strategist" | "content" | "asset" | "analyst" | "distributor" | "researcher";
  status: "running" | "succeeded" | "failed";
  input: unknown;
  output: unknown;
  error: string | null;
  startedAt: string;
  completedAt: string | null;
  durationMs: number | null;
  imageUrls: string[];
};

export type JobView = {
  id: string;
  engine: "custom" | "vercel" | "cloudflare";
  engineRunRef: string | null;
  threadRef: string | null;
  userId: string | null;
  userMessage: string;
  kind: "campaign" | "single_post" | "asset" | "analysis" | "publish" | "research" | "other";
  status: "running" | "completed" | "failed" | "queued" | "cancelled";
  currentStep: StepView["name"] | null;
  error: string | null;
  startedAt: string;
  completedAt: string | null;
  steps: StepView[];
  linkedContent: { id: string; title: string; status: string } | null;
  // Latest approval decision for the linked content, when known. Used to
  // distinguish "approval timed out" from "reviewer requested changes" /
  // "rejected" — all three end with content.status === "draft" otherwise.
  latestApprovalDecision:
    | "approved"
    | "changes_requested"
    | "rejected"
    | null;
  // Count of agent-authored revisions on the linked content_id. Renders as
  // "N/MAX" next to the Approval pill so reviewers can see how many auto-
  // revision passes a run has consumed. Kept in sync with MAX_REVISIONS in
  // apps/web/workflows/single-post.ts.
  agentRevisionCount: number;
  linkedCampaign: { id: string; name: string; slug: string } | null;
  // Resolved at dispatch time (override → settings → default) and snapshotted
  // onto workflow_runs.input. Null only for very old rows written before the
  // dispatcher began persisting the resolved id.
  model: { id: string; label: string; provider: LlmProvider | null } | null;
  // Variants the asset step generated for the linked content. Populated for
  // any engine — used to preview images on Vercel/Cloudflare cards that
  // don't stream per-step rows.
  contentAssets: Array<{
    id: string;
    kind: string;
    mimeType: string | null;
    signedUrl: string | null;
  }>;
};

const STEP_LABEL: Record<StepView["name"], string> = {
  strategist: "Strategist",
  content: "Content",
  asset: "Asset",
  analyst: "Analyst",
  distributor: "Distributor",
  researcher: "Researcher",
};

const STEP_HINT: Record<StepView["name"], string> = {
  strategist: "Plans the campaign brief and calendar",
  content: "Drafts or revises the post body",
  asset: "Generates visuals (poster, hero, og)",
  analyst: "Pulls performance numbers and learnings",
  distributor: "Schedules an approved post for a channel",
  researcher: "Searches the public web and writes findings to the KB",
};

const KIND_LABEL: Record<JobView["kind"], string> = {
  campaign: "Campaign",
  single_post: "Single post",
  asset: "Asset",
  analysis: "Analysis",
  publish: "Publish",
  research: "Research",
  other: "Workflow",
};

const RECENT_STATUS_FILTERS = [
  { value: "all", label: "All" },
  { value: "completed", label: "Completed" },
  { value: "failed", label: "Failed" },
] as const;
type RecentStatusFilter = (typeof RECENT_STATUS_FILTERS)[number]["value"];

const KIND_FILTERS: Array<{ value: JobView["kind"] | "all"; label: string }> = [
  { value: "all", label: "All kinds" },
  { value: "campaign", label: "Campaign" },
  { value: "single_post", label: "Single post" },
  { value: "asset", label: "Asset" },
  { value: "analysis", label: "Analysis" },
  { value: "publish", label: "Publish" },
  { value: "other", label: "Other" },
];

type Tab = "active" | "recent";

export function JobsView({ jobs }: { jobs: JobView[] }) {
  const [tab, setTab] = useState<Tab>("active");
  const [recentStatus, setRecentStatus] = useState<RecentStatusFilter>("all");
  const [kindFilter, setKindFilter] = useState<JobView["kind"] | "all">("all");

  const isActive = (j: JobView) =>
    j.status === "running" || j.status === "queued";

  const activeAll = jobs.filter(isActive);
  const recentAll = jobs.filter((j) => !isActive(j));

  // If the user lands with no active runs, default the tab to Recent.
  useEffect(() => {
    if (activeAll.length === 0 && tab === "active" && recentAll.length > 0) {
      setTab("recent");
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeAll.length === 0, recentAll.length === 0]);

  const tabPool = tab === "active" ? activeAll : recentAll;

  const kindCounts = new Map<JobView["kind"], number>();
  for (const j of tabPool) kindCounts.set(j.kind, (kindCounts.get(j.kind) ?? 0) + 1);

  const recentStatusCounts: Record<RecentStatusFilter, number> = {
    all: recentAll.length,
    completed: recentAll.filter((j) => j.status === "completed").length,
    failed: recentAll.filter((j) => j.status === "failed").length,
  };

  const filtered = useMemo(() => {
    return tabPool.filter((j) => {
      if (kindFilter !== "all" && j.kind !== kindFilter) return false;
      if (tab === "recent" && recentStatus !== "all" && j.status !== recentStatus)
        return false;
      return true;
    });
  }, [tabPool, kindFilter, tab, recentStatus]);

  return (
    <div className="space-y-4">
      <div
        role="tablist"
        aria-label="Workflow runs"
        className="flex items-center gap-1 border-b border-zinc-200 dark:border-zinc-800"
      >
        <TabButton
          active={tab === "active"}
          onClick={() => setTab("active")}
          count={activeAll.length}
          tone="info"
        >
          Active
        </TabButton>
        <TabButton
          active={tab === "recent"}
          onClick={() => setTab("recent")}
          count={recentAll.length}
        >
          Recent
        </TabButton>
      </div>

      <div className="surface flex flex-wrap items-center gap-x-4 gap-y-2 px-3 py-2.5">
        {tab === "recent" && (
          <>
            <FilterGroup label="Status">
              {RECENT_STATUS_FILTERS.map((f) => (
                <FilterChip
                  key={f.value}
                  active={recentStatus === f.value}
                  onClick={() => setRecentStatus(f.value)}
                  count={recentStatusCounts[f.value]}
                >
                  {f.label}
                </FilterChip>
              ))}
            </FilterGroup>
            <span className="h-4 w-px bg-zinc-200 dark:bg-zinc-800" />
          </>
        )}
        <FilterGroup label="Kind">
          {KIND_FILTERS.map((f) => {
            const count =
              f.value === "all" ? tabPool.length : (kindCounts.get(f.value) ?? 0);
            if (f.value !== "all" && count === 0 && kindFilter !== f.value) {
              return null;
            }
            return (
              <FilterChip
                key={f.value}
                active={kindFilter === f.value}
                onClick={() => setKindFilter(f.value)}
                count={count}
              >
                {f.label}
              </FilterChip>
            );
          })}
        </FilterGroup>
        {(kindFilter !== "all" || (tab === "recent" && recentStatus !== "all")) && (
          <button
            type="button"
            onClick={() => {
              setKindFilter("all");
              setRecentStatus("all");
            }}
            className="ml-auto text-xs text-zinc-500 hover:text-zinc-700 dark:hover:text-zinc-300 underline"
          >
            Clear filters
          </button>
        )}
      </div>

      <Section
        subtitle={
          tab === "active"
            ? "In flight right now"
            : "Last 50 — completed or failed"
        }
        empty={
          tab === "active"
            ? "Nothing running"
            : kindFilter !== "all" || recentStatus !== "all"
              ? "No runs match the current filters"
              : "No recent jobs"
        }
        count={filtered.length}
      >
        {filtered.map((j) => (
          <JobCard key={j.id} job={j} />
        ))}
      </Section>
    </div>
  );
}

function TabButton({
  active,
  onClick,
  count,
  tone,
  children,
}: {
  active: boolean;
  onClick: () => void;
  count: number;
  tone?: "info";
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      role="tab"
      aria-selected={active}
      onClick={onClick}
      className={[
        "relative -mb-px inline-flex items-center gap-2 px-3 py-2 text-sm font-medium transition-colors",
        active
          ? "border-b-2 border-[var(--accent)] text-ink"
          : "border-b-2 border-transparent text-mid hover:text-ink",
      ].join(" ")}
    >
      <span>{children}</span>
      <span
        className={[
          "inline-flex min-w-[1.25rem] items-center justify-center rounded-full px-1.5 text-[10px] font-semibold tabular-nums",
          active
            ? tone === "info"
              ? "bg-[var(--accent-soft)] text-[var(--accent)]"
              : "bg-[var(--accent-soft)] text-ink"
            : "bg-zinc-100 text-zinc-500 dark:bg-zinc-800 dark:text-zinc-400",
        ].join(" ")}
      >
        {count}
      </span>
    </button>
  );
}

function FilterGroup({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-wrap items-center gap-1.5">
      <span className="text-[10px] font-semibold uppercase tracking-wider text-zinc-400">
        {label}
      </span>
      {children}
    </div>
  );
}

function FilterChip({
  active,
  count,
  onClick,
  children,
}: {
  active: boolean;
  count: number;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={[
        "inline-flex items-center gap-1.5 rounded-md border px-2 py-0.5 text-xs transition-colors",
        active
          ? "border-[var(--accent)] bg-[var(--accent-soft)] text-ink"
          : "border-[var(--border)] bg-[var(--surface)] text-mid hover:border-[var(--border-strong)] hover:text-ink",
      ].join(" ")}
    >
      <span>{children}</span>
      <span
        className={[
          "rounded px-1 text-[10px] font-medium tabular-nums",
          active
            ? "bg-white/40 text-ink dark:bg-black/30"
            : "bg-zinc-100 text-zinc-500 dark:bg-zinc-800 dark:text-zinc-400",
        ].join(" ")}
      >
        {count}
      </span>
    </button>
  );
}

function Section({
  title,
  subtitle,
  empty,
  count,
  children,
}: {
  title?: string;
  subtitle: string;
  empty: string;
  count?: number;
  children: React.ReactNode;
}) {
  const items = Array.isArray(children) ? children : [children];
  const hasAny = items.some((c) => c !== null && c !== undefined && c !== false);
  return (
    <section>
      {(title || count !== undefined) && (
        <div className="flex items-baseline justify-between mb-3">
          <div>
            {title && (
              <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-500">
                {title}
              </h2>
            )}
            <p className="text-xs text-zinc-400">
              {subtitle}
              {count !== undefined && (
                <span> · {count} {count === 1 ? "result" : "results"}</span>
              )}
            </p>
          </div>
        </div>
      )}
      {hasAny ? (
        <div className="space-y-4">{children}</div>
      ) : (
        <div className="rounded-xl border border-dashed border-zinc-200 dark:border-zinc-800 px-4 py-8 text-center text-sm text-zinc-400">
          {empty}
        </div>
      )}
    </section>
  );
}

function JobCard({ job }: { job: JobView }) {
  const [expanded, setExpanded] = useState(job.status === "running");
  const [composerOpen, setComposerOpen] = useState(false);

  // A campaign-plan run only fires the Strategist by design. Once it has
  // produced a linked campaign, surface a one-click way to kick off the
  // next stage (Content sub-agent against that campaign) without re-typing
  // the campaign id into the top form.
  const canContinueAsPost =
    job.kind === "campaign" &&
    job.status === "completed" &&
    job.linkedCampaign !== null;

  // Build a pipeline row that includes pending placeholders for step names
  // not yet started, so the visual progression doesn't suddenly jump.
  // Researcher is rendered only when it actually ran, since most jobs don't
  // touch it — keeping it out of the placeholder list avoids a permanent
  // ghost slot on every campaign/post run.
  const pipelineNames: StepView["name"][] = [
    ...(job.steps.some((s) => s.name === "researcher") ? (["researcher"] as const) : []),
    "strategist",
    "content",
    "asset",
    "analyst",
    "distributor",
  ];
  const ranByName = new Map(job.steps.map((s) => [s.name, s] as const));

  return (
    <article className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900">
      <header className="px-5 py-4 border-b border-zinc-100 dark:border-zinc-800 flex items-start justify-between gap-4">
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 text-xs text-zinc-500 mb-1">
            <EngineChip engine={job.engine} />
            <KindChip kind={job.kind} />
            <StatusChip status={job.status} />
            {job.model && <ModelChip model={job.model} />}
            {job.linkedCampaign && (
              <span className="truncate">
                · campaign{" "}
                <span className="font-medium text-zinc-700 dark:text-zinc-300">
                  {job.linkedCampaign.name}
                </span>
              </span>
            )}
            {job.linkedContent && (
              <span className="truncate">
                · content{" "}
                <span className="font-medium text-zinc-700 dark:text-zinc-300">
                  {job.linkedContent.title}
                </span>
              </span>
            )}
          </div>
          <p className="text-sm text-zinc-900 dark:text-zinc-100 font-medium leading-snug">
            {job.userMessage.length > 240
              ? `${job.userMessage.slice(0, 240)}…`
              : job.userMessage}
          </p>
          <div className="mt-1 text-xs text-zinc-400 flex flex-wrap gap-x-3 gap-y-0.5">
            <span>
              started <RelativeTime iso={job.startedAt} />
            </span>
            {job.completedAt && (
              <span>
                · finished <RelativeTime iso={job.completedAt} /> ·{" "}
                {formatDuration(
                  new Date(job.completedAt).getTime() -
                    new Date(job.startedAt).getTime(),
                )}
              </span>
            )}
            {job.userId && <span>· {job.userId}</span>}
            {job.threadRef && <span>· {job.threadRef}</span>}
          </div>
        </div>
        <div className="shrink-0 flex items-center gap-2">
          {canContinueAsPost && (
            <button
              type="button"
              onClick={() => setComposerOpen((v) => !v)}
              className="rounded-md border border-blue-300 bg-blue-50 px-2 py-1 text-xs font-medium text-blue-700 hover:bg-blue-100 dark:border-blue-900/60 dark:bg-blue-950/40 dark:text-blue-300 dark:hover:bg-blue-900/40"
            >
              {composerOpen ? "Cancel" : "Continue → Draft post"}
            </button>
          )}
          {(job.status === "failed" || job.status === "cancelled") && (
            <RetryButton
              jobId={job.id}
              // Cancelled-with-changes_requested means the auto-revise loop
              // had reviewer feedback to work from. The retry endpoint now
              // resumes against the existing content row in that case, so
              // the button copy should match: "Resume revising" instead of
              // a generic Retry that reads like a redo from scratch.
              mode={
                job.status === "cancelled" &&
                job.latestApprovalDecision === "changes_requested" &&
                job.linkedContent &&
                (job.linkedContent.status === "draft" ||
                  job.linkedContent.status === "in_review")
                  ? "resume_revising"
                  : "retry"
              }
            />
          )}
          <button
            type="button"
            onClick={() => setExpanded((v) => !v)}
            className="rounded-md border border-zinc-200 dark:border-zinc-700 px-2 py-1 text-xs text-zinc-600 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800"
          >
            {expanded ? "Hide details" : "Show details"}
          </button>
        </div>
      </header>

      {composerOpen && job.linkedCampaign && (
        <ContinueAsPostComposer
          campaignId={job.linkedCampaign.id}
          campaignName={job.linkedCampaign.name}
          onDone={() => setComposerOpen(false)}
        />
      )}

      {/* Pipeline / engine-specific status. Custom is the only engine
          that streams per-sub-agent step rows; for Vercel/Cloudflare we
          render an engine-aware status block instead so the card doesn't
          look stuck on five empty placeholder pills. */}
      {job.engine === "custom" ? (
        <div className="px-5 py-4 flex flex-wrap gap-2 items-center">
          {pipelineNames.map((name, idx) => {
            const step = ranByName.get(name);
            const isCurrent = job.currentStep === name;
            return (
              <div key={name} className="flex items-center gap-2">
                <PipelinePill
                  name={name}
                  step={step}
                  isCurrent={isCurrent && job.status === "running"}
                />
                {idx < pipelineNames.length - 1 && (
                  <span className="text-zinc-300 dark:text-zinc-700">→</span>
                )}
              </div>
            );
          })}
        </div>
      ) : (
        <ExternalEngineStatus job={job} />
      )}

      {expanded && (
        <div className="border-t border-zinc-100 dark:border-zinc-800 divide-y divide-zinc-100 dark:divide-zinc-800">
          {job.engine === "custom" && job.steps.length === 0 && (
            <div className="px-5 py-4 text-sm text-zinc-400">
              Waiting for the first sub-agent to start.
            </div>
          )}
          {job.steps.map((step) => (
            <StepDetail key={step.id} step={step} />
          ))}
          {job.engine !== "custom" && (
            <div className="px-5 py-4 space-y-2 text-sm text-zinc-500 dark:text-zinc-400">
              <p>
                This run executes inside the {job.engine === "vercel" ? "Vercel" : "Cloudflare"}{" "}
                Workflows runtime as a single durable step that wraps the
                sub-agent's tool loop. Per-tool detail isn't streamed back
                here — inspect it via the Workflows inspector instead.
              </p>
              {job.contentAssets.length > 0 && (
                <AssetVariantsStrip assets={job.contentAssets} />
              )}
              {job.engineRunRef && (
                <p className="font-mono text-xs">
                  runId: <span className="text-zinc-700 dark:text-zinc-300">{job.engineRunRef}</span>
                </p>
              )}
              {job.engine === "vercel" && (
                <p className="text-xs">
                  Locally:{" "}
                  <code className="rounded bg-zinc-100 dark:bg-zinc-800 px-1 py-0.5">
                    pnpm --filter web exec workflow web
                  </code>
                </p>
              )}
            </div>
          )}
          {job.error && (
            <div className="px-5 py-4 text-sm text-red-600 dark:text-red-400">
              <strong className="font-medium">Job error:</strong> {job.error}
            </div>
          )}
        </div>
      )}
    </article>
  );
}

// Inferred phase pipeline for engines that don't stream per-sub-agent rows
// (Vercel / Cloudflare). We derive the current phase from observable DB
// side-effects: a content row appearing, asset variants appearing, the
// content's status moving past `in_review`, and the workflow_runs status.
// This way the dashboard reflects the real progress of the workflow body
// even though it's wrapped as a single durable step.
type ExternalPhase = {
  key: string;
  label: string;
  status: "succeeded" | "running" | "failed" | "needs_revision" | "pending";
  hint: string;
};

function inferExternalPhases(job: JobView): ExternalPhase[] {
  const isRunning = job.status === "running" || job.status === "queued";
  const isCompleted = job.status === "completed";
  const isFailed = job.status === "failed";
  const isCancelled = job.status === "cancelled";

  if (job.kind === "campaign") {
    return [
      {
        key: "strategist",
        label: "Strategist",
        status: isCompleted
          ? "succeeded"
          : isFailed
            ? "failed"
            : isRunning
              ? "running"
              : "pending",
        hint: "Plans the campaign brief and calendar",
      },
    ];
  }

  if (job.kind === "asset") {
    return [
      {
        key: "asset",
        label: "Asset",
        status: isCompleted
          ? "succeeded"
          : isFailed
            ? "failed"
            : isRunning
              ? "running"
              : "pending",
        hint: "Generates a visual from the brief",
      },
    ];
  }

  if (job.kind === "single_post") {
    const hasContent = !!job.linkedContent;
    const hasAssets = job.contentAssets.length > 0;
    const cs = job.linkedContent?.status ?? null;
    const inReview = cs === "in_review";
    const approved =
      cs === "approved" || cs === "published" || cs === "scheduled";
    const rejected =
      cs === "rejected" || job.latestApprovalDecision === "rejected";
    const changesRequested =
      job.latestApprovalDecision === "changes_requested" && cs === "draft";
    // After 7-day timeout the workflow drops content back to "draft" with no
    // recorded decision. (changesRequested also lands on "draft" — disambiguate
    // via the approval decision.)
    const timedOut =
      isCancelled && cs === "draft" && !changesRequested && !rejected;

    return [
      {
        key: "draft",
        label: "Draft",
        status: hasContent
          ? "succeeded"
          : isFailed
            ? "failed"
            : isRunning
              ? "running"
              : "pending",
        hint: "Drafts the post body",
      },
      {
        key: "assets",
        label: "Assets",
        status: hasAssets
          ? "succeeded"
          : !hasContent
            ? "pending"
            : isFailed
              ? "failed"
              : isRunning
                ? "running"
                : "pending",
        hint: "Generates 3 image variants",
      },
      {
        key: "approval",
        label: "Approval",
        status: approved
          ? "succeeded"
          : rejected || timedOut
            ? "failed"
            : changesRequested
              ? "needs_revision"
              : !hasAssets
                ? "pending"
                : inReview && isRunning
                  ? "running"
                  : "pending",
        hint: timedOut
          ? "Approval timed out"
          : rejected
            ? "Reviewer rejected the draft"
            : changesRequested
              ? isRunning
                ? "Reviewer requested changes — revising"
                : "Reviewer requested changes — max revisions reached"
              : "Awaiting human review",
      },
      {
        key: "publish",
        label: "Publish",
        status: isCompleted
          ? "succeeded"
          : approved && isRunning
            ? "running"
            : isFailed && approved
              ? "failed"
              : "pending",
        hint: "Publish to the channel",
      },
    ];
  }

  return [
    {
      key: "run",
      label: "Run",
      status: isCompleted
        ? "succeeded"
        : isFailed
          ? "failed"
          : isRunning
            ? "running"
            : "pending",
      hint: "Workflow body",
    },
  ];
}

function ExternalEngineStatus({ job }: { job: JobView }) {
  const phases = inferExternalPhases(job);
  const renderableAssets = job.contentAssets.filter((a) => a.signedUrl);
  const currentPhase = phases.find((p) => p.status === "running");
  const failedPhase = phases.find((p) => p.status === "failed");
  const revisionPhase = phases.find((p) => p.status === "needs_revision");

  let footnote: { tone: "info" | "success" | "warn" | "danger"; text: string } | null = null;
  if (failedPhase) {
    footnote = {
      tone: "danger",
      text: job.error ?? `${failedPhase.label} failed`,
    };
  } else if (revisionPhase) {
    // Distinct from failed: changes_requested is a normal outcome that loops
    // back into a revision pass (or terminates with "max revisions reached").
    footnote = { tone: "warn", text: revisionPhase.hint };
  } else if (currentPhase) {
    footnote = { tone: "info", text: currentPhase.hint };
  } else if (job.status === "completed") {
    footnote = { tone: "success", text: "Workflow completed" };
  } else if (job.status === "cancelled") {
    footnote = { tone: "warn", text: job.error ?? "Cancelled" };
  }

  const footnoteCls =
    footnote?.tone === "danger"
      ? "text-red-600 dark:text-red-400"
      : footnote?.tone === "success"
        ? "text-emerald-600 dark:text-emerald-400"
        : footnote?.tone === "warn"
          ? "text-amber-600 dark:text-amber-400"
          : "text-zinc-500 dark:text-zinc-400";

  return (
    <div className="px-5 py-4 space-y-3 text-sm">
      <div className="flex flex-wrap items-center gap-2">
        {phases.map((p, idx) => (
          <div key={p.key} className="flex items-center gap-2">
            <ExternalPhasePill phase={p} />
            {p.key === "approval" && job.agentRevisionCount > 0 && (
              <RevisionCountBadge count={job.agentRevisionCount} />
            )}
            {idx < phases.length - 1 && (
              <span className="text-zinc-300 dark:text-zinc-700">→</span>
            )}
          </div>
        ))}
      </div>
      {footnote && <p className={`text-xs ${footnoteCls}`}>{footnote.text}</p>}
      {renderableAssets.length > 0 && (
        <AssetVariantsStrip assets={renderableAssets} />
      )}
    </div>
  );
}

// MAX_REVISIONS in apps/web/workflows/single-post.ts. Keep in sync — the
// chip needs the denominator to render "N/MAX". Importing across the
// workflow boundary risks dragging "use workflow" runtime into the RSC.
const MAX_REVISIONS_DISPLAY = 3;

function RevisionCountBadge({ count }: { count: number }) {
  const exhausted = count >= MAX_REVISIONS_DISPLAY;
  const tone = exhausted
    ? "border-red-200 dark:border-red-900/60 bg-red-50 dark:bg-red-900/30 text-red-700 dark:text-red-300"
    : "border-amber-200 dark:border-amber-900/60 bg-amber-50 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300";
  return (
    <span
      title={
        exhausted
          ? "Max auto-revisions consumed"
          : "Auto-revisions consumed / cap"
      }
      className={`inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-medium tabular-nums ${tone}`}
    >
      rev {count}/{MAX_REVISIONS_DISPLAY}
    </span>
  );
}

function ExternalPhasePill({ phase }: { phase: ExternalPhase }) {
  const tone =
    phase.status === "running"
      ? "border-blue-200 dark:border-blue-900/60 bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300"
      : phase.status === "succeeded"
        ? "border-emerald-200 dark:border-emerald-900/60 bg-emerald-50 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300"
        : phase.status === "failed"
          ? "border-red-200 dark:border-red-900/60 bg-red-50 dark:bg-red-900/30 text-red-700 dark:text-red-300"
          : phase.status === "needs_revision"
            ? "border-amber-200 dark:border-amber-900/60 bg-amber-50 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300"
            : "border-zinc-200 dark:border-zinc-800 text-zinc-400";
  return (
    <span
      title={phase.hint}
      className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium ${tone}`}
    >
      <StepDot status={phase.status} pulsing={phase.status === "running"} />
      {phase.label}
    </span>
  );
}

// Renders the asset-step output as a compact thumbnail strip. Used by both
// the collapsed and expanded vercel/cloudflare cards. Videos render with a
// `muted` autoplaying preview because Veo MP4s have no native poster.
function AssetVariantsStrip({
  assets,
}: {
  assets: Array<{
    id: string;
    kind: string;
    mimeType: string | null;
    signedUrl: string | null;
  }>;
}) {
  const renderable = assets.filter((a) => a.signedUrl);
  if (renderable.length === 0) return null;
  return (
    <div className="flex flex-wrap gap-2">
      {renderable.slice(0, 6).map((a) => {
        const isVideo =
          (a.mimeType ?? "").startsWith("video/") || a.kind === "video_post";
        return (
          <a
            key={a.id}
            href={a.signedUrl!}
            target="_blank"
            rel="noopener noreferrer"
            title={`${a.kind}${isVideo ? " (video)" : ""}`}
            className="block h-20 w-20 overflow-hidden rounded-md border border-zinc-200 dark:border-zinc-700 bg-zinc-50 dark:bg-zinc-800"
          >
            {isVideo ? (
              <video
                src={a.signedUrl!}
                muted
                playsInline
                preload="metadata"
                className="h-full w-full object-cover"
              />
            ) : (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={a.signedUrl!}
                alt={a.kind}
                className="h-full w-full object-cover"
              />
            )}
          </a>
        );
      })}
    </div>
  );
}

// Retry control surfaced in the JobCard header for failed/cancelled runs.
// Re-dispatches via /api/workflow-runs/[id]/retry — that route reads the
// snapshotted input off workflow_runs and re-resolves the model from
// current settings, so a settings change between attempts (e.g. switching
// off an out-of-quota provider) takes effect on the new run.
//
// `mode` switches the copy + tooltip. The retry endpoint now resumes
// in-place against the linked content row when the prior run died with
// reviewer feedback — so the button reads "Resume revising" in that case
// instead of a generic "Retry" that implies a redo from scratch.
function RetryButton({
  jobId,
  mode,
}: {
  jobId: string;
  mode: "retry" | "resume_revising";
}) {
  const router = useRouter();
  const [submitting, setSubmitting] = useState(false);
  const [isPending, startTransition] = useTransition();

  const onClick = async () => {
    setSubmitting(true);
    const toastId = toast.loading(
      mode === "resume_revising" ? "Resuming revision…" : "Retrying run…",
    );
    try {
      const res = await fetch(`/api/workflow-runs/${jobId}/retry`, {
        method: "POST",
        headers: { "content-type": "application/json" },
      });
      const data = (await res.json().catch(() => ({}))) as {
        error?: string;
        message?: string;
        reason?: string;
        provider?: string;
        model?: string;
      };
      if (!res.ok) {
        const detail =
          data.message ?? data.error ?? `Server returned ${res.status}.`;
        const title =
          data.error === "llm_preflight_failed"
            ? `LLM preflight failed${data.provider ? ` (${data.provider})` : ""}`
            : "Retry failed";
        toast.error(title, { id: toastId, description: detail });
        return;
      }
      toast.success(
        mode === "resume_revising"
          ? "Revision resumed"
          : "Retry dispatched",
        {
          id: toastId,
          description:
            mode === "resume_revising"
              ? "A new run was queued against the same draft, continuing from the reviewer's last feedback."
              : "A new run has been queued with current model settings.",
        },
      );
      startTransition(() => router.refresh());
    } catch (err) {
      toast.error("Retry failed", {
        id: toastId,
        description: (err as Error).message,
      });
    } finally {
      setSubmitting(false);
    }
  };

  const title =
    mode === "resume_revising"
      ? "Continues revising the same draft using the reviewer's latest changes_requested feedback."
      : "Re-dispatch this run with the current model settings";
  const label =
    mode === "resume_revising"
      ? submitting
        ? "Resuming…"
        : "Resume revising"
      : submitting
        ? "Retrying…"
        : "Retry";

  return (
    <button
      type="button"
      onClick={onClick}
      disabled={submitting || isPending}
      title={title}
      className="rounded-md border border-amber-300 bg-amber-50 px-2 py-1 text-xs font-medium text-amber-800 hover:bg-amber-100 disabled:cursor-not-allowed disabled:opacity-60 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-300 dark:hover:bg-amber-900/40"
    >
      {label}
    </button>
  );
}

function ContinueAsPostComposer({
  campaignId,
  campaignName,
  onDone,
}: {
  campaignId: string;
  campaignName: string;
  onDone: () => void;
}) {
  const router = useRouter();
  const [request, setRequest] = useState("");
  const [channel, setChannel] = useState<Channel | "">("");
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const [submitting, setSubmitting] = useState(false);

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    if (!request.trim()) {
      setError("Brief is required.");
      return;
    }
    setSubmitting(true);
    try {
      const body: Record<string, unknown> = {
        kind: "single_post",
        request: request.trim(),
        campaignId,
      };
      if (channel) body.channel = channel;
      const res = await fetch("/api/generation-jobs/start", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        const data = (await res.json().catch(() => ({}))) as { error?: string };
        setError(data.error ?? `Server returned ${res.status}.`);
        return;
      }
      onDone();
      startTransition(() => router.refresh());
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <form
      onSubmit={onSubmit}
      className="border-t border-zinc-100 dark:border-zinc-800 bg-blue-50/40 dark:bg-blue-950/20 px-5 py-4 space-y-3"
    >
      <div className="text-xs text-zinc-600 dark:text-zinc-400">
        Drafts a single post for{" "}
        <span className="font-medium text-zinc-800 dark:text-zinc-200">
          {campaignName}
        </span>{" "}
        via the Content sub-agent. Runs in the background and appears as a new
        card above.
      </div>
      <textarea
        value={request}
        onChange={(e) => setRequest(e.target.value)}
        rows={3}
        required
        placeholder="e.g. LinkedIn post announcing the new RAG benchmarks. Punchy, data-led."
        className="w-full rounded border border-zinc-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-900"
      />
      <div className="flex flex-wrap items-center gap-3">
        <label className="text-xs text-zinc-600 dark:text-zinc-400">
          Channel{" "}
          <select
            value={channel}
            onChange={(e) => setChannel(e.target.value as Channel | "")}
            className="ml-1 rounded border border-zinc-300 bg-white px-2 py-1 text-xs dark:border-zinc-700 dark:bg-zinc-900"
          >
            <option value="">(let the agent decide)</option>
            {CHANNELS.map((c) => (
              <option key={c} value={c}>
                {c}
              </option>
            ))}
          </select>
        </label>
        <button
          type="submit"
          disabled={submitting || isPending}
          className="rounded bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:bg-zinc-400"
        >
          {submitting ? "Starting…" : "Start draft"}
        </button>
        {error && (
          <span className="text-xs text-red-600 dark:text-red-400">{error}</span>
        )}
      </div>
    </form>
  );
}

function StepDetail({ step }: { step: StepView }) {
  return (
    <div className="px-5 py-4">
      <div className="flex items-center justify-between gap-3 mb-2">
        <div className="flex items-center gap-2">
          <StepDot status={step.status} />
          <span className="text-sm font-medium">{STEP_LABEL[step.name]}</span>
          <span className="text-xs text-zinc-400">{STEP_HINT[step.name]}</span>
        </div>
        <div className="text-xs text-zinc-400">
          {step.durationMs !== null
            ? formatDuration(step.durationMs)
            : step.status === "running"
              ? "running…"
              : ""}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
        <Panel title="Planning input">
          <PreBlock value={step.input} />
        </Panel>
        <Panel title={step.status === "failed" ? "Error" : "Output"}>
          {step.status === "failed" ? (
            <pre className="whitespace-pre-wrap break-words text-red-600 dark:text-red-400 leading-snug">
              {step.error ?? "(no error message)"}
            </pre>
          ) : (
            <PreBlock value={step.output} />
          )}
        </Panel>
      </div>

      {step.imageUrls.length > 0 && (
        <div className="mt-3">
          <div className="text-[11px] uppercase tracking-wide text-zinc-400 mb-1.5">
            Generated images
          </div>
          <div className="flex flex-wrap gap-2">
            {step.imageUrls.map((url) => (
              <a
                key={url}
                href={url}
                target="_blank"
                rel="noopener noreferrer"
                className="block rounded-md overflow-hidden border border-zinc-200 dark:border-zinc-800 hover:border-zinc-400 dark:hover:border-zinc-600"
              >
                {/* Use plain <img> so we don't need next/image domain config. */}
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={url}
                  alt="Generated asset"
                  className="block h-32 w-32 object-cover bg-zinc-100 dark:bg-zinc-800"
                />
              </a>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function Panel({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-md border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900/40">
      <div className="px-3 py-1.5 border-b border-zinc-200 dark:border-zinc-800 text-[10px] uppercase tracking-wide text-zinc-500">
        {title}
      </div>
      <div className="p-3 max-h-56 overflow-auto">{children}</div>
    </div>
  );
}

function PreBlock({ value }: { value: unknown }) {
  const text = useMemo(() => formatJsonish(value), [value]);
  if (!text) {
    return <span className="text-zinc-400">—</span>;
  }
  return (
    <pre className="whitespace-pre-wrap break-words leading-snug text-zinc-700 dark:text-zinc-300">
      {text}
    </pre>
  );
}

function PipelinePill({
  name,
  step,
  isCurrent,
}: {
  name: StepView["name"];
  step: StepView | undefined;
  isCurrent: boolean;
}) {
  let className =
    "inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium border ";
  if (!step) {
    className += "border-zinc-200 dark:border-zinc-800 text-zinc-400";
  } else if (step.status === "running" || isCurrent) {
    className +=
      "border-blue-200 dark:border-blue-900/60 bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300";
  } else if (step.status === "succeeded") {
    className +=
      "border-emerald-200 dark:border-emerald-900/60 bg-emerald-50 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300";
  } else if (step.status === "failed") {
    className +=
      "border-red-200 dark:border-red-900/60 bg-red-50 dark:bg-red-900/30 text-red-700 dark:text-red-300";
  } else {
    className += "border-zinc-200 dark:border-zinc-800 text-zinc-500";
  }
  return (
    <span className={className}>
      <StepDot status={step?.status ?? "pending"} pulsing={isCurrent} />
      {STEP_LABEL[name]}
    </span>
  );
}

function StepDot({
  status,
  pulsing,
}: {
  status: StepView["status"] | "pending" | "needs_revision";
  pulsing?: boolean;
}) {
  const color =
    status === "succeeded"
      ? "bg-emerald-500"
      : status === "failed"
        ? "bg-red-500"
        : status === "running"
          ? "bg-blue-500"
          : status === "needs_revision"
            ? "bg-amber-500"
            : "bg-zinc-300 dark:bg-zinc-700";
  return (
    <span className={`relative inline-block h-2 w-2 rounded-full ${color}`}>
      {pulsing && (
        <span className="absolute inset-0 rounded-full bg-blue-500 opacity-60 animate-ping" />
      )}
    </span>
  );
}

function StatusChip({ status }: { status: JobView["status"] }) {
  const map: Record<JobView["status"], string> = {
    queued:
      "bg-zinc-100 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300",
    running:
      "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300",
    completed:
      "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300",
    failed: "bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300",
    cancelled:
      "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300",
  };
  return (
    <span
      className={`inline-flex rounded-full px-2 py-0.5 text-[11px] font-medium ${map[status]}`}
    >
      {status}
    </span>
  );
}

function KindChip({ kind }: { kind: JobView["kind"] }) {
  return (
    <span className="inline-flex rounded-full bg-zinc-100 dark:bg-zinc-800 px-2 py-0.5 text-[11px] font-medium text-zinc-700 dark:text-zinc-300">
      {KIND_LABEL[kind]}
    </span>
  );
}

function ModelChip({
  model,
}: {
  model: NonNullable<JobView["model"]>;
}) {
  // Provider-tinted so the strategist's pick is scannable at a glance —
  // Anthropic / OpenAI / Google rows look distinct.
  const styles: Record<LlmProvider | "unknown", string> = {
    anthropic:
      "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300",
    openai:
      "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300",
    google:
      "bg-sky-100 text-sky-800 dark:bg-sky-900/30 dark:text-sky-300",
    unknown:
      "bg-zinc-100 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300",
  };
  const tone = styles[model.provider ?? "unknown"];
  return (
    <span
      title={model.id}
      className={`inline-flex rounded-full px-2 py-0.5 text-[11px] font-medium ${tone}`}
    >
      {model.label}
    </span>
  );
}

function EngineChip({ engine }: { engine: JobView["engine"] }) {
  const styles: Record<JobView["engine"], string> = {
    custom:
      "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300",
    vercel: "bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900",
    cloudflare:
      "bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300",
  };
  const label =
    engine === "custom" ? "Custom" : engine === "vercel" ? "Vercel" : "Cloudflare";
  return (
    <span
      className={`inline-flex rounded-full px-2 py-0.5 text-[11px] font-medium ${styles[engine]}`}
    >
      {label}
    </span>
  );
}

// --- formatting -----------------------------------------------------------

function formatJsonish(value: unknown): string {
  if (value === null || value === undefined) return "";
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
}

function formatDuration(ms: number): string {
  if (!Number.isFinite(ms) || ms < 0) return "";
  if (ms < 1000) return `${ms}ms`;
  const seconds = ms / 1000;
  if (seconds < 60) return `${seconds.toFixed(1)}s`;
  const minutes = Math.floor(seconds / 60);
  const remSeconds = Math.round(seconds % 60);
  return `${minutes}m ${remSeconds}s`;
}

function formatRelative(iso: string): string {
  const then = new Date(iso).getTime();
  if (!Number.isFinite(then)) return "";
  const diff = Date.now() - then;
  if (diff < 60_000) return `${Math.max(1, Math.floor(diff / 1000))}s ago`;
  if (diff < 3_600_000) return `${Math.floor(diff / 60_000)}m ago`;
  if (diff < 86_400_000) return `${Math.floor(diff / 3_600_000)}h ago`;
  return new Date(iso).toLocaleString();
}

// Hydration-safe relative time: "use client" components still SSR once on
// first render, and Date.now() during SSR vs hydration can land on different
// integer seconds, producing "8s" vs "9s" mismatches. Rendering empty on the
// server and filling in on mount keeps server/client text identical, then a
// 5s interval keeps it ticking while a job is in flight.
function RelativeTime({ iso }: { iso: string }) {
  const [text, setText] = useState("");
  useEffect(() => {
    const update = () => setText(formatRelative(iso));
    update();
    const id = setInterval(update, 5000);
    return () => clearInterval(id);
  }, [iso]);
  return <>{text}</>;
}
