"use client";

// Client renderer for the /creation-workflow page. Splits jobs into
// "Active" (running or just-finished) and "Recent" sections, renders each
// as a step pipeline with planning input, output preview, and any image
// thumbnails generated by the asset sub-agent.
//
// State only — no fetch logic here. The server component re-runs on
// realtime invalidation (RealtimeInvalidator subscribes to the table).

import { useEffect, useMemo, useState, useTransition, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import {
  CHANNELS,
  type Channel,
  type LlmProvider,
  type WorkflowMedia,
} from "@marketing/shared-types";

export type StepView = {
  id: string;
  name: "strategist" | "content" | "asset" | "analyst" | "distributor" | "researcher";
  status: "running" | "succeeded" | "failed";
  input: unknown;
  output: unknown;
  error: string | null;
  startedAt: string;
  completedAt: string | null;
  durationMs: number | null;
  imageUrls: string[];
};

export type JobView = {
  id: string;
  engine: "custom" | "vercel" | "cloudflare";
  engineRunRef: string | null;
  threadRef: string | null;
  userId: string | null;
  userMessage: string;
  kind:
    | "campaign"
    | "execute_campaign"
    | "single_post"
    | "asset"
    | "analysis"
    | "publish"
    | "research"
    | "other";
  status: "running" | "completed" | "failed" | "queued" | "cancelled";
  currentStep: StepView["name"] | null;
  error: string | null;
  startedAt: string;
  completedAt: string | null;
  steps: StepView[];
  linkedContent: { id: string; title: string; status: string } | null;
  // Latest approval decision for the linked content, when known. Used to
  // distinguish "approval timed out" from "reviewer requested changes" /
  // "rejected" — all three end with content.status === "draft" otherwise.
  latestApprovalDecision:
    | "approved"
    | "changes_requested"
    | "rejected"
    | null;
  // Count of agent-authored revisions on the linked content_id. Renders as
  // "N/MAX" next to the Approval pill so reviewers can see how many auto-
  // revision passes a run has consumed. Kept in sync with MAX_REVISIONS in
  // apps/web/workflows/single-post.ts.
  agentRevisionCount: number;
  linkedCampaign: { id: string; name: string; slug: string } | null;
  // Resolved at dispatch time (override → settings → default) and snapshotted
  // onto workflow_runs.input. Null only for very old rows written before the
  // dispatcher began persisting the resolved id.
  model: { id: string; label: string; provider: LlmProvider | null } | null;
  // User-chosen media for this run (snapshotted onto workflow_runs.input).
  // Null when the run kind doesn't accept a media override (e.g. campaign,
  // research) or for older rows written before the field was persisted.
  media: WorkflowMedia | null;
  // Variants the asset step generated for the linked content. Populated for
  // any engine — used to preview images on Vercel/Cloudflare cards that
  // don't stream per-step rows.
  contentAssets: Array<{
    id: string;
    kind: string;
    mimeType: string | null;
    signedUrl: string | null;
  }>;
};

const STEP_LABEL: Record<StepView["name"], string> = {
  strategist: "Strategist",
  content: "Content",
  asset: "Asset",
  analyst: "Analyst",
  distributor: "Distributor",
  researcher: "Researcher",
};

const STEP_HINT: Record<StepView["name"], string> = {
  strategist: "Plans the campaign brief and calendar",
  content: "Drafts or revises the post body",
  asset: "Generates visuals (poster, hero, og)",
  analyst: "Pulls performance numbers and learnings",
  distributor: "Schedules an approved post for a channel",
  researcher: "Searches the public web and writes findings to the KB",
};

const KIND_LABEL: Record<JobView["kind"], string> = {
  campaign: "Campaign",
  execute_campaign: "Execute campaign",
  single_post: "Single post",
  asset: "Asset",
  analysis: "Analysis",
  publish: "Publish",
  research: "Research",
  other: "Workflow",
};

const RECENT_STATUS_FILTERS = [
  { value: "all", label: "All" },
  { value: "completed", label: "Completed" },
  { value: "failed", label: "Failed" },
] as const;
type RecentStatusFilter = (typeof RECENT_STATUS_FILTERS)[number]["value"];

const KIND_FILTERS: Array<{ value: JobView["kind"] | "all"; label: string }> = [
  { value: "all", label: "All kinds" },
  { value: "campaign", label: "Campaign" },
  { value: "execute_campaign", label: "Execute campaign" },
  { value: "single_post", label: "Single post" },
  { value: "asset", label: "Asset" },
  { value: "analysis", label: "Analysis" },
  { value: "publish", label: "Publish" },
  { value: "other", label: "Other" },
];

type Tab = "active" | "recent";

export function JobsView({ jobs }: { jobs: JobView[] }) {
  const [tab, setTab] = useState<Tab>("active");
  const [recentStatus, setRecentStatus] = useState<RecentStatusFilter>("all");
  const [kindFilter, setKindFilter] = useState<JobView["kind"] | "all">("all");

  const isActive = (j: JobView) =>
    j.status === "running" || j.status === "queued";

  const activeAll = jobs.filter(isActive);
  const recentAll = jobs.filter((j) => !isActive(j));

  // If the user lands with no active runs, default the tab to Recent.
  useEffect(() => {
    if (activeAll.length === 0 && tab === "active" && recentAll.length > 0) {
      setTab("recent");
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeAll.length === 0, recentAll.length === 0]);

  const tabPool = tab === "active" ? activeAll : recentAll;

  const kindCounts = new Map<JobView["kind"], number>();
  for (const j of tabPool) kindCounts.set(j.kind, (kindCounts.get(j.kind) ?? 0) + 1);

  const recentStatusCounts: Record<RecentStatusFilter, number> = {
    all: recentAll.length,
    completed: recentAll.filter((j) => j.status === "completed").length,
    failed: recentAll.filter((j) => j.status === "failed").length,
  };

  const filtered = useMemo(() => {
    return tabPool.filter((j) => {
      if (kindFilter !== "all" && j.kind !== kindFilter) return false;
      if (tab === "recent" && recentStatus !== "all" && j.status !== recentStatus)
        return false;
      return true;
    });
  }, [tabPool, kindFilter, tab, recentStatus]);

  return (
    <div className="space-y-4">
      <div
        role="tablist"
        aria-label="Workflow runs"
        className="flex items-center gap-1 border-b border-zinc-200 dark:border-zinc-800"
      >
        <TabButton
          active={tab === "active"}
          onClick={() => setTab("active")}
          count={activeAll.length}
          tone="info"
        >
          Active
        </TabButton>
        <TabButton
          active={tab === "recent"}
          onClick={() => setTab("recent")}
          count={recentAll.length}
        >
          Recent
        </TabButton>
      </div>

      <div className="surface flex flex-wrap items-center gap-x-4 gap-y-2 px-3 py-2.5">
        {tab === "recent" && (
          <>
            <FilterGroup label="Status">
              {RECENT_STATUS_FILTERS.map((f) => (
                <FilterChip
                  key={f.value}
                  active={recentStatus === f.value}
                  onClick={() => setRecentStatus(f.value)}
                  count={recentStatusCounts[f.value]}
                >
                  {f.label}
                </FilterChip>
              ))}
            </FilterGroup>
            <span className="h-4 w-px bg-zinc-200 dark:bg-zinc-800" />
          </>
        )}
        <FilterGroup label="Kind">
          {KIND_FILTERS.map((f) => {
            const count =
              f.value === "all" ? tabPool.length : (kindCounts.get(f.value) ?? 0);
            if (f.value !== "all" && count === 0 && kindFilter !== f.value) {
              return null;
            }
            return (
              <FilterChip
                key={f.value}
                active={kindFilter === f.value}
                onClick={() => setKindFilter(f.value)}
                count={count}
              >
                {f.label}
              </FilterChip>
            );
          })}
        </FilterGroup>
        {(kindFilter !== "all" || (tab === "recent" && recentStatus !== "all")) && (
          <button
            type="button"
            onClick={() => {
              setKindFilter("all");
              setRecentStatus("all");
            }}
            className="ml-auto text-xs text-zinc-500 hover:text-zinc-700 dark:hover:text-zinc-300 underline"
          >
            Clear filters
          </button>
        )}
      </div>

      <Section
        empty={
          tab === "active"
            ? "Nothing running"
            : kindFilter !== "all" || recentStatus !== "all"
              ? "No runs match the current filters"
              : "No recent jobs"
        }
      >
        {filtered.map((j) => (
          <JobCard key={j.id} job={j} />
        ))}
      </Section>
    </div>
  );
}

function TabButton({
  active,
  onClick,
  count,
  tone,
  children,
}: {
  active: boolean;
  onClick: () => void;
  count: number;
  tone?: "info";
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      role="tab"
      aria-selected={active}
      onClick={onClick}
      className={[
        "relative -mb-px inline-flex items-center gap-2 px-3 py-2 text-sm font-medium transition-colors",
        active
          ? "border-b-2 border-[var(--accent)] text-ink"
          : "border-b-2 border-transparent text-mid hover:text-ink",
      ].join(" ")}
    >
      <span>{children}</span>
      <span
        className={[
          "inline-flex min-w-[1.25rem] items-center justify-center rounded-full px-1.5 text-[10px] font-semibold tabular-nums",
          active
            ? tone === "info"
              ? "bg-[var(--accent-soft)] text-[var(--accent)]"
              : "bg-[var(--accent-soft)] text-ink"
            : "bg-zinc-100 text-zinc-500 dark:bg-zinc-800 dark:text-zinc-400",
        ].join(" ")}
      >
        {count}
      </span>
    </button>
  );
}

function FilterGroup({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-wrap items-center gap-1.5">
      <span className="text-[10px] font-semibold uppercase tracking-wider text-zinc-400">
        {label}
      </span>
      {children}
    </div>
  );
}

function FilterChip({
  active,
  count,
  onClick,
  children,
}: {
  active: boolean;
  count: number;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={[
        "inline-flex items-center gap-1.5 rounded-md border px-2 py-0.5 text-xs transition-colors",
        active
          ? "border-[var(--accent)] bg-[var(--accent-soft)] text-ink"
          : "border-[var(--border)] bg-[var(--surface)] text-mid hover:border-[var(--border-strong)] hover:text-ink",
      ].join(" ")}
    >
      <span>{children}</span>
      <span
        className={[
          "rounded px-1 text-[10px] font-medium tabular-nums",
          active
            ? "bg-white/40 text-ink dark:bg-black/30"
            : "bg-zinc-100 text-zinc-500 dark:bg-zinc-800 dark:text-zinc-400",
        ].join(" ")}
      >
        {count}
      </span>
    </button>
  );
}

function Section({
  empty,
  children,
}: {
  empty: string;
  children: React.ReactNode;
}) {
  const items = Array.isArray(children) ? children : [children];
  const hasAny = items.some((c) => c !== null && c !== undefined && c !== false);
  return (
    <section>
      {hasAny ? (
        <div className="space-y-4">{children}</div>
      ) : (
        <div className="rounded-xl border border-dashed border-zinc-200 dark:border-zinc-800 px-4 py-8 text-center text-sm text-zinc-400">
          {empty}
        </div>
      )}
    </section>
  );
}

function JobCard({ job }: { job: JobView }) {
  const [expanded, setExpanded] = useState(false);
  const [composerOpen, setComposerOpen] = useState(false);

  // A campaign-plan run only fires the Strategist by design. Once it has
  // produced a linked campaign, surface a one-click way to kick off the
  // next stage (Content sub-agent against that campaign) without re-typing
  // the campaign id into the top form.
  const canContinueAsPost =
    job.kind === "campaign" &&
    job.status === "completed" &&
    job.linkedCampaign !== null;

  // Build a pipeline row that includes pending placeholders for step names
  // not yet started, so the visual progression doesn't suddenly jump.
  // Researcher is rendered only when it actually ran, since most jobs don't
  // touch it — keeping it out of the placeholder list avoids a permanent
  // ghost slot on every campaign/post run.
  const pipelineNames: StepView["name"][] = [
    ...(job.steps.some((s) => s.name === "researcher") ? (["researcher"] as const) : []),
    "strategist",
    "content",
    "asset",
    "analyst",
    "distributor",
  ];
  const ranByName = new Map(job.steps.map((s) => [s.name, s] as const));

  return (
    <article className="group relative overflow-hidden rounded-xl border border-border bg-surface shadow-sm transition-colors hover:border-border-strong">
      {/* Left-edge accent — gives each card an at-a-glance status read */}
      <span
        aria-hidden
        className={`absolute inset-y-0 left-0 w-0.75 ${statusAccentClass(job.status)}`}
      />

      <header className="flex items-start justify-between gap-4 px-5 pl-6 pt-4 pb-3">
        <div className="min-w-0 flex-1 space-y-2.5">
          {/* Compact meta strip: status, kind, model, engine — separated
              from the title so the title can breathe. */}
          <div className="flex flex-wrap items-center gap-1.5">
            <StatusPill status={job.status} />
            <KindChip kind={job.kind} />
            {job.media && <MediaChip media={job.media} />}
            {job.model && <ModelChip model={job.model} />}
            <EngineChip engine={job.engine} />
            <span className="ml-auto inline-flex items-center gap-1 text-[11px] text-faint tabular-nums">
              <RelativeTime iso={job.startedAt} />
              {job.completedAt && (
                <>
                  <span className="text-border-strong">·</span>
                  <span>
                    {formatDuration(
                      new Date(job.completedAt).getTime() -
                        new Date(job.startedAt).getTime(),
                    )}
                  </span>
                </>
              )}
            </span>
          </div>

          <h3 className="text-[15px] font-semibold leading-snug text-ink line-clamp-2">
            {job.userMessage}
          </h3>

          {(job.linkedCampaign || job.linkedContent) && (
            <div className="flex flex-wrap items-center gap-1.5">
              {job.linkedCampaign && (
                <LinkedEntityPill
                  kind="campaign"
                  label={job.linkedCampaign.name}
                />
              )}
              {job.linkedContent && (
                <LinkedEntityPill
                  kind="content"
                  label={job.linkedContent.title}
                />
              )}
            </div>
          )}
        </div>

        <div className="shrink-0 flex items-center gap-1.5">
          {canContinueAsPost && (
            <button
              type="button"
              onClick={() => setComposerOpen((v) => !v)}
              className="inline-flex items-center gap-1 rounded-md border border-accent bg-(--accent-soft) px-2.5 py-1 text-xs font-medium text-accent hover:bg-(--accent-soft) hover:brightness-110"
            >
              {composerOpen ? "Cancel" : "Draft post →"}
            </button>
          )}
          {(job.status === "failed" || job.status === "cancelled") && (
            <RetryButton
              jobId={job.id}
              // Cancelled-with-changes_requested means the auto-revise loop
              // had reviewer feedback to work from. The retry endpoint now
              // resumes against the existing content row in that case, so
              // the button copy should match: "Resume revising" instead of
              // a generic Retry that reads like a redo from scratch.
              mode={
                job.status === "cancelled" &&
                job.latestApprovalDecision === "changes_requested" &&
                job.linkedContent &&
                (job.linkedContent.status === "draft" ||
                  job.linkedContent.status === "in_review")
                  ? "resume_revising"
                  : "retry"
              }
            />
          )}
          <button
            type="button"
            onClick={() => setExpanded((v) => !v)}
            aria-expanded={expanded}
            className="inline-flex items-center gap-1 rounded-md border border-border bg-surface-2 px-2.5 py-1 text-xs font-medium text-mid hover:border-border-strong hover:text-ink"
          >
            <span>{expanded ? "Hide" : "Details"}</span>
            <ChevronIcon open={expanded} />
          </button>
        </div>
      </header>

      {composerOpen && job.linkedCampaign && (
        <ContinueAsPostComposer
          campaignId={job.linkedCampaign.id}
          campaignName={job.linkedCampaign.name}
          onDone={() => setComposerOpen(false)}
        />
      )}

      {/* Pipeline / engine-specific status. Custom is the only engine
          that streams per-sub-agent step rows; for Vercel/Cloudflare we
          render an engine-aware status block instead so the card doesn't
          look stuck on five empty placeholder pills. */}
      {job.engine === "custom" ? (
        <div className="px-5 pl-6 pb-4">
          <Stepper
            steps={pipelineNames.map((name) => {
              const step = ranByName.get(name);
              const isCurrent =
                job.currentStep === name && job.status === "running";
              return {
                key: name,
                label: STEP_LABEL[name],
                hint: STEP_HINT[name],
                status: !step
                  ? "pending"
                  : step.status === "running" || isCurrent
                    ? "running"
                    : step.status,
                pulsing: isCurrent,
              };
            })}
          />
        </div>
      ) : (
        <ExternalEngineStatus job={job} />
      )}

      {expanded && (
        <div className="border-t border-border divide-y divide-border bg-surface-2">
          {job.engine === "custom" && job.steps.length === 0 && (
            <div className="px-5 pl-6 py-4 text-sm text-faint">
              Waiting for the first sub-agent to start.
            </div>
          )}
          {job.steps.map((step) => (
            <StepDetail key={step.id} step={step} />
          ))}
          {job.engine !== "custom" && (
            <div className="px-5 pl-6 py-4 space-y-3 text-xs text-mid">
              {job.contentAssets.length > 0 && (
                <AssetVariantsStrip assets={job.contentAssets} />
              )}
              {job.engineRunRef && (
                <div className="inline-flex items-center gap-1.5 rounded-md border border-border bg-surface px-2 py-1 font-mono text-[11px]">
                  <span className="text-faint">runId</span>
                  <span className="text-ink">{job.engineRunRef}</span>
                </div>
              )}
            </div>
          )}
          {job.error && (
            <div className="px-5 pl-6 py-3 text-sm text-red-600 dark:text-red-400">
              <strong className="font-medium">Job error:</strong> {job.error}
            </div>
          )}
        </div>
      )}
    </article>
  );
}

// Maps run status to a tailwind bg-* class for the left-edge accent strip.
// Running uses the accent variable so it matches the app's brand; the other
// states use distinct hues so a glance down a list of cards reads:
// "two running, one done, one in trouble."
function statusAccentClass(status: JobView["status"]): string {
  switch (status) {
    case "running":
    case "queued":
      return "bg-[var(--accent)]";
    case "completed":
      return "bg-emerald-500";
    case "failed":
      return "bg-red-500";
    case "cancelled":
      return "bg-amber-500";
    default:
      return "bg-[var(--border)]";
  }
}

function ChevronIcon({ open }: { open: boolean }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="12"
      height="12"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={`transition-transform ${open ? "rotate-180" : ""}`}
      aria-hidden
    >
      <polyline points="6 9 12 15 18 9" />
    </svg>
  );
}

function LinkedEntityPill({
  kind,
  label,
}: {
  kind: "campaign" | "content";
  label: string;
}) {
  const icon =
    kind === "campaign" ? (
      <svg
        viewBox="0 0 24 24"
        width="12"
        height="12"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
      >
        <circle cx="12" cy="12" r="9" />
        <circle cx="12" cy="12" r="5" />
        <circle cx="12" cy="12" r="1.5" />
      </svg>
    ) : (
      <svg
        viewBox="0 0 24 24"
        width="12"
        height="12"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
      >
        <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
        <path d="M14 2v6h6" />
        <path d="M8 13h8M8 17h5" />
      </svg>
    );
  return (
    <span
      title={label}
      className="inline-flex max-w-full items-center gap-1.5 rounded-md border border-border bg-surface-2 px-2 py-0.5 text-[11px] text-mid"
    >
      <span className="text-faint">{icon}</span>
      <span className="text-[10px] uppercase tracking-wider text-faint">
        {kind}
      </span>
      <span className="truncate font-medium text-ink max-w-[18rem]">
        {label}
      </span>
    </span>
  );
}

// Inferred phase pipeline for engines that don't stream per-sub-agent rows
// (Vercel / Cloudflare). We derive the current phase from observable DB
// side-effects: a content row appearing, asset variants appearing, the
// content's status moving past `in_review`, and the workflow_runs status.
// This way the dashboard reflects the real progress of the workflow body
// even though it's wrapped as a single durable step.
type ExternalPhase = {
  key: string;
  label: string;
  status: "succeeded" | "running" | "failed" | "needs_revision" | "pending";
  hint: string;
};

function inferExternalPhases(job: JobView): ExternalPhase[] {
  const isRunning = job.status === "running" || job.status === "queued";
  const isCompleted = job.status === "completed";
  const isFailed = job.status === "failed";
  const isCancelled = job.status === "cancelled";

  if (job.kind === "campaign") {
    return [
      {
        key: "strategist",
        label: "Strategist",
        status: isCompleted
          ? "succeeded"
          : isFailed
            ? "failed"
            : isRunning
              ? "running"
              : "pending",
        hint: "Plans the campaign brief and calendar",
      },
    ];
  }

  if (job.kind === "asset") {
    return [
      {
        key: "asset",
        label: "Asset",
        status: isCompleted
          ? "succeeded"
          : isFailed
            ? "failed"
            : isRunning
              ? "running"
              : "pending",
        hint: "Generates a visual from the brief",
      },
    ];
  }

  if (job.kind === "single_post") {
    const hasContent = !!job.linkedContent;
    const hasAssets = job.contentAssets.length > 0;
    const cs = job.linkedContent?.status ?? null;
    const inReview = cs === "in_review";
    const approved =
      cs === "approved" || cs === "published" || cs === "scheduled";
    const rejected =
      cs === "rejected" || job.latestApprovalDecision === "rejected";
    const changesRequested =
      job.latestApprovalDecision === "changes_requested" && cs === "draft";
    // After 7-day timeout the workflow drops content back to "draft" with no
    // recorded decision. (changesRequested also lands on "draft" — disambiguate
    // via the approval decision.)
    const timedOut =
      isCancelled && cs === "draft" && !changesRequested && !rejected;

    return [
      {
        key: "draft",
        label: "Draft",
        status: hasContent
          ? "succeeded"
          : isFailed
            ? "failed"
            : isRunning
              ? "running"
              : "pending",
        hint: "Drafts the post body",
      },
      {
        key: "assets",
        label: "Assets",
        status: hasAssets
          ? "succeeded"
          : !hasContent
            ? "pending"
            : isFailed
              ? "failed"
              : isRunning
                ? "running"
                : "pending",
        hint: "Generates 3 image variants",
      },
      {
        key: "approval",
        label: "Approval",
        status: approved
          ? "succeeded"
          : rejected || timedOut
            ? "failed"
            : changesRequested
              ? "needs_revision"
              : !hasAssets
                ? "pending"
                : inReview && isRunning
                  ? "running"
                  : "pending",
        hint: timedOut
          ? "Approval timed out"
          : rejected
            ? "Reviewer rejected the draft"
            : changesRequested
              ? isRunning
                ? "Reviewer requested changes — revising"
                : "Reviewer requested changes — max revisions reached"
              : "Awaiting human review",
      },
      {
        key: "publish",
        label: "Publish",
        status: isCompleted
          ? "succeeded"
          : approved && isRunning
            ? "running"
            : isFailed && approved
              ? "failed"
              : "pending",
        hint: "Publish to the channel",
      },
    ];
  }

  return [
    {
      key: "run",
      label: "Run",
      status: isCompleted
        ? "succeeded"
        : isFailed
          ? "failed"
          : isRunning
            ? "running"
            : "pending",
      hint: "Workflow body",
    },
  ];
}

function ExternalEngineStatus({ job }: { job: JobView }) {
  const phases = inferExternalPhases(job);
  const renderableAssets = job.contentAssets.filter((a) => a.signedUrl);
  const failedPhase = phases.find((p) => p.status === "failed");
  const revisionPhase = phases.find((p) => p.status === "needs_revision");

  // Only show a footnote when there's signal beyond the pills themselves
  // (failed/cancelled/changes-requested). Running/completed are already
  // conveyed by the pill colors + status chip.
  let footnote: { tone: "info" | "success" | "warn" | "danger"; text: string } | null = null;
  if (failedPhase) {
    footnote = {
      tone: "danger",
      text: job.error ?? `${failedPhase.label} failed`,
    };
  } else if (revisionPhase) {
    footnote = { tone: "warn", text: revisionPhase.hint };
  } else if (job.status === "cancelled") {
    footnote = { tone: "warn", text: job.error ?? "Cancelled" };
  }

  const footnoteCls =
    footnote?.tone === "danger"
      ? "text-red-600 dark:text-red-400"
      : footnote?.tone === "success"
        ? "text-emerald-600 dark:text-emerald-400"
        : footnote?.tone === "warn"
          ? "text-amber-600 dark:text-amber-400"
          : "text-mid";

  return (
    <div className="space-y-3 px-5 pl-6 pb-4">
      <Stepper
        steps={phases.map((p) => ({
          key: p.key,
          label: p.label,
          hint: p.hint,
          status: p.status,
          pulsing: p.status === "running",
          adornment:
            p.key === "approval" && job.agentRevisionCount > 0 ? (
              <RevisionCountBadge count={job.agentRevisionCount} />
            ) : null,
        }))}
      />
      {footnote && <p className={`text-xs ${footnoteCls}`}>{footnote.text}</p>}
      {renderableAssets.length > 0 && (
        <AssetVariantsStrip assets={renderableAssets} />
      )}
    </div>
  );
}

// MAX_REVISIONS in apps/web/workflows/single-post.ts. Keep in sync — the
// chip needs the denominator to render "N/MAX". Importing across the
// workflow boundary risks dragging "use workflow" runtime into the RSC.
const MAX_REVISIONS_DISPLAY = 3;

function RevisionCountBadge({ count }: { count: number }) {
  const exhausted = count >= MAX_REVISIONS_DISPLAY;
  const tone = exhausted
    ? "border-red-200 dark:border-red-900/60 bg-red-50 dark:bg-red-900/30 text-red-700 dark:text-red-300"
    : "border-amber-200 dark:border-amber-900/60 bg-amber-50 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300";
  return (
    <span
      title={
        exhausted
          ? "Max auto-revisions consumed"
          : "Auto-revisions consumed / cap"
      }
      className={`inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-medium tabular-nums ${tone}`}
    >
      rev {count}/{MAX_REVISIONS_DISPLAY}
    </span>
  );
}

// --- Stepper -------------------------------------------------------------
//
// Horizontal stepper used for both custom-engine sub-agent pipelines and
// the inferred phase pipeline for external engines. The connector line
// between steps is colored by the destination step's progress: a finished
// step → next finished step gets a solid emerald line; running gets the
// accent; pending stays a muted gutter. The result is that the bar reads
// as a progress meter in addition to the pill labels.

type StepperStepStatus =
  | "succeeded"
  | "running"
  | "failed"
  | "needs_revision"
  | "pending";

type StepperStep = {
  key: string;
  label: string;
  hint?: string;
  status: StepperStepStatus;
  pulsing?: boolean;
  adornment?: ReactNode;
};

function Stepper({ steps }: { steps: StepperStep[] }) {
  return (
    <ol className="flex flex-wrap items-center gap-y-2">
      {steps.map((step, idx) => {
        const next = steps[idx + 1];
        return (
          <li key={step.key} className="flex min-w-0 items-center">
            <StepperPill step={step} index={idx} />
            {step.adornment && (
              <span className="ml-1.5 flex items-center">{step.adornment}</span>
            )}
            {next && <StepperConnector nextStatus={next.status} />}
          </li>
        );
      })}
    </ol>
  );
}

function StepperPill({ step, index }: { step: StepperStep; index: number }) {
  const { tone, ring } = stepperPillTones(step.status);
  return (
    <span
      title={step.hint}
      className={`relative inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium ${tone}`}
    >
      <span className={`relative inline-flex h-4 w-4 items-center justify-center rounded-full ${ring}`}>
        <StepperGlyph status={step.status} index={index} />
        {step.pulsing && (
          <span className="absolute inset-0 animate-ping rounded-full bg-current opacity-40" />
        )}
      </span>
      <span>{step.label}</span>
    </span>
  );
}

function StepperGlyph({
  status,
  index,
}: {
  status: StepperStepStatus;
  index: number;
}) {
  if (status === "succeeded") {
    return (
      <svg
        viewBox="0 0 12 12"
        width="10"
        height="10"
        fill="none"
        stroke="currentColor"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
      >
        <polyline points="2.5,6.5 5,9 9.5,3.5" />
      </svg>
    );
  }
  if (status === "failed") {
    return (
      <svg
        viewBox="0 0 12 12"
        width="9"
        height="9"
        fill="none"
        stroke="currentColor"
        strokeWidth="2.5"
        strokeLinecap="round"
        aria-hidden
      >
        <line x1="3" y1="3" x2="9" y2="9" />
        <line x1="9" y1="3" x2="3" y2="9" />
      </svg>
    );
  }
  if (status === "needs_revision") {
    return (
      <svg
        viewBox="0 0 12 12"
        width="9"
        height="9"
        fill="currentColor"
        aria-hidden
      >
        <circle cx="6" cy="6" r="2" />
      </svg>
    );
  }
  if (status === "running") {
    return <span className="h-1.5 w-1.5 rounded-full bg-current" />;
  }
  // Pending — show the step number so the pipeline reads as 1-2-3-…
  return (
    <span className="text-[9px] font-semibold tabular-nums">{index + 1}</span>
  );
}

function StepperConnector({ nextStatus }: { nextStatus: StepperStepStatus }) {
  const cls =
    nextStatus === "succeeded"
      ? "bg-emerald-400/70 dark:bg-emerald-500/60"
      : nextStatus === "running"
        ? "bg-(--accent)/70"
        : nextStatus === "failed"
          ? "bg-red-400/70 dark:bg-red-500/60"
          : nextStatus === "needs_revision"
            ? "bg-amber-400/70 dark:bg-amber-500/60"
            : "bg-border";
  return (
    <span
      aria-hidden
      className={`mx-1.5 inline-block h-px w-5 sm:w-7 ${cls}`}
    />
  );
}

function stepperPillTones(status: StepperStepStatus): {
  tone: string;
  ring: string;
} {
  switch (status) {
    case "succeeded":
      return {
        tone:
          "border-emerald-300/40 bg-emerald-50 text-emerald-700 dark:border-emerald-700/40 dark:bg-emerald-900/30 dark:text-emerald-300",
        ring: "bg-emerald-500 text-white",
      };
    case "running":
      return {
        tone:
          "border-(--accent)/40 bg-(--accent-soft) text-accent dark:bg-(--accent-soft) dark:text-accent",
        ring: "bg-(--accent) text-white",
      };
    case "failed":
      return {
        tone:
          "border-red-300/40 bg-red-50 text-red-700 dark:border-red-700/40 dark:bg-red-900/30 dark:text-red-300",
        ring: "bg-red-500 text-white",
      };
    case "needs_revision":
      return {
        tone:
          "border-amber-300/40 bg-amber-50 text-amber-700 dark:border-amber-700/40 dark:bg-amber-900/30 dark:text-amber-300",
        ring: "bg-amber-500 text-white",
      };
    default:
      return {
        tone: "border-border bg-surface-2 text-faint",
        ring: "bg-surface-3 text-faint",
      };
  }
}

// Renders the asset-step output as a compact thumbnail strip. Used by both
// the collapsed and expanded vercel/cloudflare cards. Videos render with a
// `muted` autoplaying preview because Veo MP4s have no native poster.
function AssetVariantsStrip({
  assets,
}: {
  assets: Array<{
    id: string;
    kind: string;
    mimeType: string | null;
    signedUrl: string | null;
  }>;
}) {
  const renderable = assets.filter((a) => a.signedUrl);
  if (renderable.length === 0) return null;
  return (
    <div className="flex flex-wrap gap-2">
      {renderable.slice(0, 6).map((a) => {
        const isVideo =
          (a.mimeType ?? "").startsWith("video/") || a.kind === "video_post";
        return (
          <a
            key={a.id}
            href={a.signedUrl!}
            target="_blank"
            rel="noopener noreferrer"
            title={`${a.kind}${isVideo ? " (video)" : ""}`}
            className="block h-20 w-20 overflow-hidden rounded-md border border-zinc-200 dark:border-zinc-700 bg-zinc-50 dark:bg-zinc-800"
          >
            {isVideo ? (
              <video
                src={a.signedUrl!}
                muted
                playsInline
                preload="metadata"
                className="h-full w-full object-cover"
              />
            ) : (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={a.signedUrl!}
                alt={a.kind}
                className="h-full w-full object-cover"
              />
            )}
          </a>
        );
      })}
    </div>
  );
}

// Retry control surfaced in the JobCard header for failed/cancelled runs.
// Re-dispatches via /api/workflow-runs/[id]/retry — that route reads the
// snapshotted input off workflow_runs and re-resolves the model from
// current settings, so a settings change between attempts (e.g. switching
// off an out-of-quota provider) takes effect on the new run.
//
// `mode` switches the copy + tooltip. The retry endpoint now resumes
// in-place against the linked content row when the prior run died with
// reviewer feedback — so the button reads "Resume revising" in that case
// instead of a generic "Retry" that implies a redo from scratch.
function RetryButton({
  jobId,
  mode,
}: {
  jobId: string;
  mode: "retry" | "resume_revising";
}) {
  const router = useRouter();
  const [submitting, setSubmitting] = useState(false);
  const [isPending, startTransition] = useTransition();

  const onClick = async () => {
    setSubmitting(true);
    const toastId = toast.loading(
      mode === "resume_revising" ? "Resuming revision…" : "Retrying run…",
    );
    try {
      const res = await fetch(`/api/workflow-runs/${jobId}/retry`, {
        method: "POST",
        headers: { "content-type": "application/json" },
      });
      const data = (await res.json().catch(() => ({}))) as {
        error?: string;
        message?: string;
        reason?: string;
        provider?: string;
        model?: string;
      };
      if (!res.ok) {
        const detail =
          data.message ?? data.error ?? `Server returned ${res.status}.`;
        const title =
          data.error === "llm_preflight_failed"
            ? `LLM preflight failed${data.provider ? ` (${data.provider})` : ""}`
            : "Retry failed";
        toast.error(title, { id: toastId, description: detail });
        return;
      }
      toast.success(
        mode === "resume_revising"
          ? "Revision resumed"
          : "Retry dispatched",
        {
          id: toastId,
          description:
            mode === "resume_revising"
              ? "A new run was queued against the same draft, continuing from the reviewer's last feedback."
              : "A new run has been queued with current model settings.",
        },
      );
      startTransition(() => router.refresh());
    } catch (err) {
      toast.error("Retry failed", {
        id: toastId,
        description: (err as Error).message,
      });
    } finally {
      setSubmitting(false);
    }
  };

  const title =
    mode === "resume_revising"
      ? "Continues revising the same draft using the reviewer's latest changes_requested feedback."
      : "Re-dispatch this run with the current model settings";
  const label =
    mode === "resume_revising"
      ? submitting
        ? "Resuming…"
        : "Resume revising"
      : submitting
        ? "Retrying…"
        : "Retry";

  return (
    <button
      type="button"
      onClick={onClick}
      disabled={submitting || isPending}
      title={title}
      className="rounded-md border border-amber-300 bg-amber-50 px-2 py-1 text-xs font-medium text-amber-800 hover:bg-amber-100 disabled:cursor-not-allowed disabled:opacity-60 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-300 dark:hover:bg-amber-900/40"
    >
      {label}
    </button>
  );
}

function ContinueAsPostComposer({
  campaignId,
  campaignName,
  onDone,
}: {
  campaignId: string;
  campaignName: string;
  onDone: () => void;
}) {
  const router = useRouter();
  const [request, setRequest] = useState("");
  const [channel, setChannel] = useState<Channel | "">("");
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const [submitting, setSubmitting] = useState(false);

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    if (!request.trim()) {
      setError("Brief is required.");
      return;
    }
    setSubmitting(true);
    try {
      const body: Record<string, unknown> = {
        kind: "single_post",
        request: request.trim(),
        campaignId,
      };
      if (channel) body.channel = channel;
      const res = await fetch("/api/generation-jobs/start", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        const data = (await res.json().catch(() => ({}))) as { error?: string };
        setError(data.error ?? `Server returned ${res.status}.`);
        return;
      }
      onDone();
      startTransition(() => router.refresh());
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <form
      onSubmit={onSubmit}
      className="border-t border-zinc-100 dark:border-zinc-800 bg-blue-50/40 dark:bg-blue-950/20 px-5 py-4 space-y-3"
    >
      <div className="text-xs text-zinc-600 dark:text-zinc-400">
        Drafts a single post for{" "}
        <span className="font-medium text-zinc-800 dark:text-zinc-200">
          {campaignName}
        </span>{" "}
        via the Content sub-agent. Runs in the background and appears as a new
        card above.
      </div>
      <textarea
        value={request}
        onChange={(e) => setRequest(e.target.value)}
        rows={3}
        required
        placeholder="e.g. LinkedIn post announcing the new RAG benchmarks. Punchy, data-led."
        className="w-full rounded border border-zinc-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-900"
      />
      <div className="flex flex-wrap items-center gap-3">
        <label className="text-xs text-zinc-600 dark:text-zinc-400">
          Channel{" "}
          <select
            value={channel}
            onChange={(e) => setChannel(e.target.value as Channel | "")}
            className="ml-1 rounded border border-zinc-300 bg-white px-2 py-1 text-xs dark:border-zinc-700 dark:bg-zinc-900"
          >
            <option value="">(let the agent decide)</option>
            {CHANNELS.map((c) => (
              <option key={c} value={c}>
                {c}
              </option>
            ))}
          </select>
        </label>
        <button
          type="submit"
          disabled={submitting || isPending}
          className="rounded bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:bg-zinc-400"
        >
          {submitting ? "Starting…" : "Start draft"}
        </button>
        {error && (
          <span className="text-xs text-red-600 dark:text-red-400">{error}</span>
        )}
      </div>
    </form>
  );
}

function StepDetail({ step }: { step: StepView }) {
  return (
    <div className="px-5 py-4">
      <div className="flex items-center justify-between gap-3 mb-2">
        <div className="flex items-center gap-2">
          <StepDot status={step.status} />
          <span className="text-sm font-medium">{STEP_LABEL[step.name]}</span>
          <span className="text-xs text-zinc-400">{STEP_HINT[step.name]}</span>
        </div>
        <div className="text-xs text-zinc-400">
          {step.durationMs !== null
            ? formatDuration(step.durationMs)
            : step.status === "running"
              ? "running…"
              : ""}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
        <Panel title="Planning input">
          <PreBlock value={step.input} />
        </Panel>
        <Panel title={step.status === "failed" ? "Error" : "Output"}>
          {step.status === "failed" ? (
            <pre className="whitespace-pre-wrap break-words text-red-600 dark:text-red-400 leading-snug">
              {step.error ?? "(no error message)"}
            </pre>
          ) : (
            <PreBlock value={step.output} />
          )}
        </Panel>
      </div>

      {step.imageUrls.length > 0 && (
        <div className="mt-3">
          <div className="text-[11px] uppercase tracking-wide text-zinc-400 mb-1.5">
            Generated images
          </div>
          <div className="flex flex-wrap gap-2">
            {step.imageUrls.map((url) => (
              <a
                key={url}
                href={url}
                target="_blank"
                rel="noopener noreferrer"
                className="block rounded-md overflow-hidden border border-zinc-200 dark:border-zinc-800 hover:border-zinc-400 dark:hover:border-zinc-600"
              >
                {/* Use plain <img> so we don't need next/image domain config. */}
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={url}
                  alt="Generated asset"
                  className="block h-32 w-32 object-cover bg-zinc-100 dark:bg-zinc-800"
                />
              </a>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function Panel({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-md border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900/40">
      <div className="px-3 py-1.5 border-b border-zinc-200 dark:border-zinc-800 text-[10px] uppercase tracking-wide text-zinc-500">
        {title}
      </div>
      <div className="p-3 max-h-56 overflow-auto">{children}</div>
    </div>
  );
}

function PreBlock({ value }: { value: unknown }) {
  const text = useMemo(() => formatJsonish(value), [value]);
  if (!text) {
    return <span className="text-zinc-400">—</span>;
  }
  return (
    <pre className="whitespace-pre-wrap break-words leading-snug text-zinc-700 dark:text-zinc-300">
      {text}
    </pre>
  );
}

function StepDot({
  status,
  pulsing,
}: {
  status: StepView["status"] | "pending" | "needs_revision";
  pulsing?: boolean;
}) {
  const color =
    status === "succeeded"
      ? "bg-emerald-500"
      : status === "failed"
        ? "bg-red-500"
        : status === "running"
          ? "bg-blue-500"
          : status === "needs_revision"
            ? "bg-amber-500"
            : "bg-zinc-300 dark:bg-zinc-700";
  return (
    <span className={`relative inline-block h-2 w-2 rounded-full ${color}`}>
      {pulsing && (
        <span className="absolute inset-0 rounded-full bg-blue-500 opacity-60 animate-ping" />
      )}
    </span>
  );
}

function StatusPill({ status }: { status: JobView["status"] }) {
  const { bg, text, dot, pulse } = statusPillTones(status);
  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full px-2 py-0.5 text-[11px] font-medium ${bg} ${text}`}
    >
      <span className={`relative inline-flex h-1.5 w-1.5 rounded-full ${dot}`}>
        {pulse && (
          <span className={`absolute inset-0 animate-ping rounded-full ${dot} opacity-60`} />
        )}
      </span>
      {status}
    </span>
  );
}

function statusPillTones(status: JobView["status"]): {
  bg: string;
  text: string;
  dot: string;
  pulse: boolean;
} {
  switch (status) {
    case "running":
      return {
        bg: "bg-(--accent-soft)",
        text: "text-accent",
        dot: "bg-(--accent)",
        pulse: true,
      };
    case "queued":
      return {
        bg: "bg-surface-2 border border-border",
        text: "text-mid",
        dot: "bg-zinc-400 dark:bg-zinc-500",
        pulse: true,
      };
    case "completed":
      return {
        bg: "bg-emerald-100 dark:bg-emerald-900/40",
        text: "text-emerald-700 dark:text-emerald-300",
        dot: "bg-emerald-500",
        pulse: false,
      };
    case "failed":
      return {
        bg: "bg-red-100 dark:bg-red-900/40",
        text: "text-red-700 dark:text-red-300",
        dot: "bg-red-500",
        pulse: false,
      };
    case "cancelled":
      return {
        bg: "bg-amber-100 dark:bg-amber-900/40",
        text: "text-amber-700 dark:text-amber-300",
        dot: "bg-amber-500",
        pulse: false,
      };
  }
}

function KindChip({ kind }: { kind: JobView["kind"] }) {
  return (
    <span className="inline-flex rounded-full bg-zinc-100 dark:bg-zinc-800 px-2 py-0.5 text-[11px] font-medium text-zinc-700 dark:text-zinc-300">
      {KIND_LABEL[kind]}
    </span>
  );
}

function ModelChip({
  model,
}: {
  model: NonNullable<JobView["model"]>;
}) {
  // Provider-tinted so the strategist's pick is scannable at a glance —
  // Anthropic / OpenAI / Google rows look distinct.
  const styles: Record<LlmProvider | "unknown", string> = {
    anthropic:
      "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300",
    openai:
      "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300",
    google:
      "bg-sky-100 text-sky-800 dark:bg-sky-900/30 dark:text-sky-300",
    unknown:
      "bg-zinc-100 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300",
  };
  const tone = styles[model.provider ?? "unknown"];
  return (
    <span
      title={model.id}
      className={`inline-flex rounded-full px-2 py-0.5 text-[11px] font-medium ${tone}`}
    >
      {model.label}
    </span>
  );
}

function MediaChip({ media }: { media: WorkflowMedia }) {
  const styles: Record<WorkflowMedia, string> = {
    auto: "bg-zinc-100 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300",
    image:
      "bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300",
    video:
      "bg-rose-100 text-rose-700 dark:bg-rose-900/40 dark:text-rose-300",
    both: "bg-fuchsia-100 text-fuchsia-700 dark:bg-fuchsia-900/40 dark:text-fuchsia-300",
  };
  const icon: Record<WorkflowMedia, ReactNode> = {
    auto: (
      <svg
        viewBox="0 0 24 24"
        width="11"
        height="11"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
      >
        <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" />
      </svg>
    ),
    image: (
      <svg
        viewBox="0 0 24 24"
        width="11"
        height="11"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
      >
        <rect x="3" y="3" width="18" height="18" rx="2" />
        <circle cx="9" cy="9" r="2" />
        <path d="M21 15l-5-5L5 21" />
      </svg>
    ),
    video: (
      <svg
        viewBox="0 0 24 24"
        width="11"
        height="11"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
      >
        <rect x="2" y="6" width="14" height="12" rx="2" />
        <path d="M22 8l-6 4 6 4z" />
      </svg>
    ),
    both: (
      <svg
        viewBox="0 0 24 24"
        width="11"
        height="11"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
      >
        <rect x="2" y="6" width="14" height="12" rx="2" />
        <path d="M22 8l-6 4 6 4z" />
      </svg>
    ),
  };
  const label: Record<WorkflowMedia, string> = {
    auto: "Auto",
    image: "Image",
    video: "Video",
    both: "Image + Video",
  };
  const tooltip: Record<WorkflowMedia, string> = {
    auto: "Auto — images by default, video only when the content type opts in",
    image: "Image only — video kickoff skipped",
    video: "Video only — image pipeline skipped",
    both: "Forced image + video, regardless of content type",
  };
  return (
    <span
      title={tooltip[media]}
      className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-medium ${styles[media]}`}
    >
      {icon[media]}
      {label[media]}
    </span>
  );
}

function EngineChip({ engine }: { engine: JobView["engine"] }) {
  const styles: Record<JobView["engine"], string> = {
    custom:
      "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300",
    vercel: "bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900",
    cloudflare:
      "bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300",
  };
  const label =
    engine === "custom" ? "Custom" : engine === "vercel" ? "Vercel" : "Cloudflare";
  return (
    <span
      className={`inline-flex rounded-full px-2 py-0.5 text-[11px] font-medium ${styles[engine]}`}
    >
      {label}
    </span>
  );
}

// --- formatting -----------------------------------------------------------

function formatJsonish(value: unknown): string {
  if (value === null || value === undefined) return "";
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
}

function formatDuration(ms: number): string {
  if (!Number.isFinite(ms) || ms < 0) return "";
  if (ms < 1000) return `${ms}ms`;
  const seconds = ms / 1000;
  if (seconds < 60) return `${seconds.toFixed(1)}s`;
  const minutes = Math.floor(seconds / 60);
  const remSeconds = Math.round(seconds % 60);
  return `${minutes}m ${remSeconds}s`;
}

function formatRelative(iso: string): string {
  const then = new Date(iso).getTime();
  if (!Number.isFinite(then)) return "";
  const diff = Date.now() - then;
  if (diff < 60_000) return `${Math.max(1, Math.floor(diff / 1000))}s ago`;
  if (diff < 3_600_000) return `${Math.floor(diff / 60_000)}m ago`;
  if (diff < 86_400_000) return `${Math.floor(diff / 3_600_000)}h ago`;
  return new Date(iso).toLocaleString();
}

// Hydration-safe relative time: "use client" components still SSR once on
// first render, and Date.now() during SSR vs hydration can land on different
// integer seconds, producing "8s" vs "9s" mismatches. Rendering empty on the
// server and filling in on mount keeps server/client text identical, then a
// 5s interval keeps it ticking while a job is in flight.
function RelativeTime({ iso }: { iso: string }) {
  const [text, setText] = useState("");
  useEffect(() => {
    const update = () => setText(formatRelative(iso));
    update();
    const id = setInterval(update, 5000);
    return () => clearInterval(id);
  }, [iso]);
  return <>{text}</>;
}
